### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by graemeleehickey** [drizopoulos/JMbayes#1]
FYI: I got the following warning message when installing the package just now:

```
fast_LAPRWM.cpp:6:14: warning: unused variable 'log2pi' [-Wunused-const-variable]
const double log2pi = std::log(2.0 * M_PI);
```

Hopefully this helps.

**Comment by graemeleehickey** [comment]
Thanks - noticed you had fixed this last night.

**Comment by drizopoulos** [comment]
Yes, thanks for reporting it.

Best,
Dimitris

Sent from my iPhone -- apologies for any typos.

18 mrt. 2017, 16:36, ο/η Graeme Hickey <notifications@github.com<mailto:notifications@github.com>> έγραψε:


Thanks - noticed you had fixed this last night.
