### ISSUE TITLE
prederrJM returns NA value

### ISSUE THREAD

**Issue by thaoz** [drizopoulos/JMbayes#10]
https://github.com/drizopoulos/JMbayes/blob/3ba136bd4f04cc53554196ca3a48dd06793e95bb/R/prederrJM.coxph.R#L54

In case there is no censoring in the data, do you  think the weight should be 0 instead of NA? or weight = NA and add rm.na = T in the sum function?

**Comment by drizopoulos** [comment]
Yes, I think this could be done.
