### ISSUE TITLE
Dynamic prediction of longitudinal outcome

### ISSUE THREAD

**Issue by JulietteOrtholand** [drizopoulos/JMbayes#100]
Hi,
Is it possible to make longitudinal predictions using `predict` function on `mvJointModelBayes` objects? It is not available on your tutorial and it sends me an error ... I have checked to use the newer package JMBayes2, but it doesn't seem to enable joint models with logit GLMM.

**Comment by drizopoulos** [comment]
JMbayes2 works with logit GLMMs.



From: JulietteOrtholand ***@***.***>
Sent: Monday, May 15, 2023 10:22 AM
To: drizopoulos/JMbayes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes] Dynamic prediction of longitudinal outcome (Issue #100)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Hi,
Is it possible to make longitudinal predictions using predict function on mvJointModelBayes objects? It is not available on your tutorial and it sends me an error ... I have checked to use the newer package JMBayes2, but it doesn't seem to enable joint models with logit GLMM.

-

**Comment by JulietteOrtholand** [comment]
Thanks for your fast answer, then if I am not mistaken, the univariate equivalent of `mvglmer` in JMBayes in JMBayes2 is `mixed_model` right? And you're supposed to set the family parameter to get the link function you want. I would like a gaussian family with a logit link function available in `mvglmer` but I cannot access it through `mixed_model` and I cannot find an equivalent in the [documentation](https://rdrr.io/r/stats/family.html). I might be looking at the wrong place.

**Comment by JulietteOrtholand** [comment]
I finally used `beta.fam()` with `mixed_model ` from JMBayes2 and it seems to work thanks anyway.
