### ISSUE TITLE
problem running fuction JointModelBayes() in JMBayes package

### ISSUE THREAD

**Issue by Jennie96Zhao** [drizopoulos/JMbayes#101]
I had this error when running
pbc2$status2 <- as.numeric(pbc2$status != "alive")
pbc2.id$status2 <- as.numeric(pbc2.id$status != "alive")
lmeFit.pbc1 <- lme(log(serBilir) ~ drug * year, data = pbc2, random = ~ year | id, method = "ML")
coxFit.pbc1 <- coxph(Surv(years, status2) ~ drug * age, data = pbc2.id, x = TRUE)
jointFit.pbc1 <- jointModelBayes(lmeFit.pbc1, coxFit.pbc1, timeVar = "year")

Error in !inherits(test, "try-error") && !opt2$convergence && eigen(opt2$hessian,  : 
  'length = 21' in coercion to 'logical(1)'

**Comment by drizopoulos** [comment]
Try JMbayes2

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: Jennie96Zhao ***@***.***>
Στάλθηκε: Monday, May 29, 2023 4:17:43 AM
Προς: drizopoulos/JMbayes ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/JMbayes] problem running fuction JointModelBayes() in JMBayes package (Issue #101)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



I had this error when running
pbc2$status2 <- as.numeric(pbc2$status != "alive")
pbc2.id$status2 <- as.numeric(pbc2.id$status != "alive")
lmeFit.pbc1 <- lme(log(serBilir) ~ drug * year, data = pbc2, random = ~ year | id, method = "ML")
coxFit.pbc1 <- coxph(Surv(years, status2) ~ drug * age, data = pbc2.id, x = TRUE)
jointFit.pbc1 <- jointModelBayes(lmeFit.pbc1, coxFit.pbc1, timeVar = "year")

Error in !inherits(test, "try-error") && !opt2$convergence && eigen(opt2$hessian, :
'length = 21' in coercion to 'logical(1)'
