### ISSUE TITLE
Error in jointModelBayes

### ISSUE THREAD

**Issue by amirabadiza921** [drizopoulos/JMbayes#103]
model.cox<-coxph(Surv(surv_time,incidenceDM)~sex15_1+age+fbs+bs2HR+waist+FHD,data=data.cox,x=T,model=TRUE)
> summary(model.cox)
Call:
coxph(formula = Surv(surv_time, incidenceDM) ~ sex15_1 + age + 
    fbs + bs2HR + waist + FHD, data = data.cox, model = TRUE, 
    x = T)

  n= 2008, number of events= 143 

                  coef exp(coef) se(coef)     z Pr(>|z|)    
sex15_1Female 0.158799  1.172102 0.175541 0.905  0.36566    
age           0.008574  1.008611 0.007475 1.147  0.25133    
fbs           0.073469  1.076235 0.009452 7.773 7.67e-15 ***
bs2HR         0.024666  1.024972 0.003078 8.013 1.12e-15 ***
waist         0.026474  1.026827 0.008140 3.252  0.00114 ** 
FHDyes        0.417987  1.518900 0.176397 2.370  0.01781 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

              exp(coef) exp(-coef) lower .95 upper .95
sex15_1Female     1.172     0.8532    0.8309     1.653
age               1.009     0.9915    0.9939     1.023
fbs               1.076     0.9292    1.0565     1.096
bs2HR             1.025     0.9756    1.0188     1.031
waist             1.027     0.9739    1.0106     1.043
FHDyes            1.519     0.6584    1.0749     2.146

Concordance= 0.848  (se = 0.015 )
Likelihood ratio test= 289.3  on 6 df,   p=<2e-16
Wald test            = 324.8  on 6 df,   p=<2e-16
Score (logrank) test = 349  on 6 df,   p=<2e-16

> fit.lm1<-lme(TSH~ time,random=~time|code,data=dataLong,control = lmeControl(opt = "optim")) 
> summary(fit.lm1)
Linear mixed-effects model fit by REML
  Data: dataLong 
       AIC      BIC    logLik
  16524.53 16566.18 -8256.265

Random effects:
 Formula: ~time | code
 Structure: General positive-definite, Log-Cholesky parametrization
            StdDev    Corr  
(Intercept) 0.8803649 (Intr)
time        0.1306290 -0.639
Residual    0.5156154       

Fixed effects:  TSH ~ time 
                Value   Std.Error   DF  t-value p-value
(Intercept) 0.3124291 0.021938791 5636 14.24094       0
time        0.1367228 0.006102113 5636 22.40581       0
 Correlation: 
     (Intr)
time -0.581

Standardized Within-Group Residuals:
         Min           Q1          Med           Q3          Max 
-13.10336838  -0.32323331   0.01626533   0.36466696   4.90983739 

Number of Observations: 7645
Number of Groups: 2008 
> fit.jm_bayesparm<-jointModelBayes(fit.lm1,model.cox,timeVar="time",param="shared-betasRE")
Error in !is.null(out$alphas) && is.na(out$alphas) : 
  'length = 2' in coercion to 'logical(1)'

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
