### ISSUE TITLE
Issue with predictions when stratifying in Cox Model

### ISSUE THREAD

**Issue by ellenerickson** [drizopoulos/JMbayes#105]
Hello! I have come across an issue that I haven't been able to find a solution for. I am trying to stratify by gender in my survival model, and I have no issues getting my jointModelBayes function to work with this. However, when I try to use survfitJM to make predictions, I get the following error:
![image](https://github.com/drizopoulos/JMbayes/assets/62446594/3fe81d4b-f232-4ada-9837-5581ae774e65)

I know this isn't an issue with how I am creating my factor variables and naming them because when I run the exact same code but just put gender as a normal predictor, the survfitJM function runs fine. Not sure if something is happening to the factor levels of the stratified variable once it has gone through jointModelBayes or if the prediction function isn't able to handle stratified variables? 

Here is some example code:

lmeFit <- lme(diameter ~ time+type, random = ~1|id, data = lme.mod2)

coxFit <- coxph(Surv(tte, ae) ~ type + age10 + strata(gender), data = cox.mod2, x = TRUE)
coxFit2 <- coxph(Surv(tte, ae) ~ type + age10 + gender, data = cox.mod2, x = TRUE)

jointFit2 <- jointModelBayes(lmeFit, coxFit, timeVar = "time")
summary(jointFit4)

jointFit4 <- jointModelBayes(lmeFit, coxFit2, timeVar = "time")
summary(jointFit2)

id <- c(1,1)
diameter <- c(40,50)
age10 <- c(5,5)
type <- factor(c("A", "A"), levels = c("A", "B"))
time <- c(0,15)
gender <- factor(c('female','female'), levels = c('female','male'))

patientdata <- data.frame(id, diameter, age10, type, time, gender)

survfitJM(jointFit2, newdata = patientdata, idVar = 'id')
#this returns an error

survfitJM(jointFit4, newdata = patientdata, idVar = 'id')
#this works just fine

**Comment by joepiekos** [comment]
I'm not sure and I use the updated package JMbayes2, but when I've had this error it's because I'm not predicting on enough new patients. I think it's because you only have females in your newdata. Maybe try do some more patients and have a mix of male and female?

**Comment by ellencravero** [comment]
@joepiekos I have tried predicting with the entire dataset (which has both males and females) and I get the same error, so I don't think it's that.

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
