### ISSUE TITLE
An error message while running mvJointModelBayes

### ISSUE THREAD

**Issue by shahmandi** [drizopoulos/JMbayes#106]
Hello,

I encountered an error message while attempting to fit the joint model to the PBC dataset. Could you kindly provide some guidance on how to troubleshoot and resolve this issue? Any advice would be greatly appreciated.

Thank you.

MixedModelFit1 <- mvglmer(list(log(serBilir) ~ year + (1 | id)), data = pbc2,
                          families = list(gaussian), seed=set.seed(2))
pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
CoxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)

JMFit1 <- mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")
summary(JMFit1)

I got this error when I ran JMFit1:

Error in crossprod(diff(DD, differences = con$diff)): "crossprod" is not a BUILTIN function
Traceback:

1. mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
