### ISSUE TITLE
Error: The seed argument is no longer supported, use set.seed() instead

### ISSUE THREAD

**Issue by chenzaoxyf** [drizopoulos/JMbayes#107]
MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year | id),
                              hepatomegaly ~ year * sex + (year | id)), data = pbc2,
                         families = list(gaussian, binomial))  代码在别的设备都能运行成功，但是在我的设备出现这个错误：”“> MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year | id),
+                               hepatomegaly ~ year * sex + (year | id)), data = pbc2,
+                          families = list(gaussian, binomial))
Error: The seed argument is no longer supported, use set.seed() instead

**Comment by drizopoulos** [comment]
Try JMbayes2

——
Professor of Biostatistics
Erasmus Medical Center Rotterdam
The Netherlands
________________________________
Από: chenzaoxyf ***@***.***>
Στάλθηκε: Monday, May 20, 2024 4:54:05 PM
Προς: drizopoulos/JMbayes ***@***.***>
Κοιν.: Subscribed ***@***.***>
Θέμα: [drizopoulos/JMbayes] Error: The seed argument is no longer supported, use set.seed() instead (Issue #107)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year | id),
hepatomegaly ~ year * sex + (year | id)), data = pbc2,
families = list(gaussian, binomial)) 代码在别的设备都能运行成功，但是在我的设备出现这个错误：”“> MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year | id),

  *

                          hepatomegaly ~ year * sex + (year | id)), data = pbc2,


  *

                     families = list(gaussian, binomial))


Error: The seed argument is no longer supported, use set.seed() instead
