### ISSUE TITLE
missing longitudinal data

### ISSUE THREAD

**Issue by quzhouxiachuan** [drizopoulos/JMbayes#13]
Hi Drizopoulos, 

How does mvglmer() utilize missing data?For example, will the row with NA be deleted or imputed in the following example? Or can mvglmer() handle missing data at all? In addition, can aucJM() deal with dataset with missing data? 

        ID_d Time cvd      SBP      TOTCHL HXDIAB SMOKER base_age   ttocvd
             1    0   0        128.0000     NA      0      1       47 46.66667
             2    0   0         134.0000     NA      0      0       57 38.33812
             3    0   0         137.0000     NA      0     NA       45 54.00958
            4    0   1         115.3333    173      0      1       33 46.91034
            5    0   0         153.0000     NA      0      0       53 30.61465
            6    0   0         184.6667    224      0      0       43 30.94593

**Comment by akse22** [comment]
Hi there, were you able to find an answer to your question? I have the same problem. thanks

**Comment by drizopoulos** [comment]
The `mvglmer()` needs at least one measurement per outcome and per subject; it doesn't matter which measurement it is (i.e., at baseline or at a later time point). Hence, it can't work if one longitudinal outcome is available for $n$ subjects whereas another one is available for $n'$ with $n' \neq n$.

Now, provided the above condition holds, `mvglmer()` works with all available data per outcome. Implicitly the missing data are imputed by the model under the missing not random assumption, with specific missing data mechanism implied by joint models.

**Comment by akse22** [comment]
Thank you ! this is helpful.

**Comment by quzhouxiachuan** [comment]
Hi 
I have a followup on this question! Even though mvglmer() works for missing data, aucJM() can not handle missing data. In this case, we can train our model in a dataset with missing data but when evaluate the model in a validation dataset, we are not able to use aucJM() bc the missingness. How would you suggest to approach this issue? 
Thanks, 
Yu

**Comment by quzhouxiachuan** [comment]
Hi 
A follow up questions on this, does aucJM function allow missing data? If not, what would you suggest to deal with missing data in your testing dataset for aucJM evaluation?

Thanks a lot in advance!

**Comment by drizopoulos** [comment]
Missing data in the outcome or covariates you mean? Missing data in the outcome should be automatically handled under the missing at random assumption but simply excluding the records with missing outcome data from the database.

**Comment by quzhouxiachuan** [comment]
Hi 
Not meant missing in outcomes but missing value in testing set when using aucJM for evaluation.  


发自我的iPhone

------------------ Original ------------------

**Comment by quzhouxiachuan** [comment]
I see! Was thinking missing in covariates. 




发自我的iPhone

------------------ Original ------------------
