### ISSUE TITLE
warning when running mvJointModelBayes

### ISSUE THREAD

**Issue by quzhouxiachuan** [drizopoulos/JMbayes#15]
Hi, 

The following waring is generated when running command
`multJMFit1 <- mvJointModelBayes(multMixedFit1, coxfit1, timeVar = "Time")`
- warnings: 1: In x * weights : longer object length is not a multiple of shorter object length     
Could you please help with that? Much appreciated! 

Thanks!

**Comment by drizopoulos** [comment]
You can ignore this message.


Sent with my iPhone - apologies for typos

**Comment by quzhouxiachuan** [comment]
Does it indicate some errors in matrix multiplication?
