### ISSUE TITLE
tve() does not work

### ISSUE THREAD

**Issue by thaoz** [drizopoulos/JMbayes#2]
I have tried to run the following example code from the package help document but it gave me an error message "Error in tve(Time, df = 8) : could not find function "tve""
 
`library(JMbayes)`
`pbc2.id$Time <- pbc2.id$years`
`pbc2.id$event <- as.numeric(pbc2.id$status != "alive")`
`MixedModelFit1 <- mvglmer(list(log(serBilir) ~ year + (year | id)), data = pbc2,
                          families = list(gaussian))`
`CoxFit1 <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)`
`JMFit_tveffect <- mvJointModelBayes(MixedModelFit1, CoxFit1, timeVar = "year",
                                    Interactions = list("log(serBilir)_value" = ~ 0 + tve(Time, df = 8)))`
`plot(JMFit_tveffect, "tv_effect")`

I am using JMbayes version 0.8-70

**Comment by drizopoulos** [comment]
Thanks for reporting this. It should work now... Let me know if not.

**Comment by thaoz** [comment]
Thank you Dimitris, it works now.
