### ISSUE TITLE
Assessment of calibration with prederrJM

### ISSUE THREAD

**Issue by studerus** [drizopoulos/JMbayes#20]
In the vignette it is said that `prederrJM` can be used to assess calibration of the model. However, isn't the prediction error - analogous to the Brier score - an overall performance measure that is affected both by discrimination and calibration (see, for example, [this paper](https://doi.org/10.1097/EDE.0b013e3181c30fb2))?

**Comment by drizopoulos** [comment]
You’re right that the Brier score can be decomposed like that; however, Wikipedia still calls it a measure of calibration: [Brier Score](https://en.m.wikipedia.org/wiki/Brier_score).
