### ISSUE TITLE
Joint models in clinical practice

### ISSUE THREAD

**Issue by studerus** [drizopoulos/JMbayes#24]
I have short question not directly related to the the JMbayes package: Are you aware of a joint model that is already routinely applied in the real world and particularly in clinical practice?

**Comment by drizopoulos** [comment]
Check http://www.drizopoulos.com/courses/Int/JMwithR_ENAR_2018.pdf slides 189 & 190 – these are medical papers that I’ve been involved in and used joint models. They are also others…

**Comment by studerus** [comment]
Thanks. I have found many medical papers in which joint models have been developed, but is still not clear to me whether any of these models is actually applied in clinical practice by clinicians, for example, with the help of an online risk calculator.

**Comment by drizopoulos** [comment]
I know that Jeremy Taylor in Michigan has made an online calculator for risk prediction based on joint models for prostate cancer - you can search online for it and he also has a paper in Biometrics about it.

In a collaboration we have at Erasmus MC for recovery after a stroke we are planning to bring such a calculator again based on joint models online soon.

**Comment by studerus** [comment]
Thanks again. I found one other paper that has implemented a joint model as online risk calculator:
https://www.ncbi.nlm.nih.gov/pubmed/28582868
