### ISSUE TITLE
survfitJM() gives error for data with tibble class 

### ISSUE THREAD

**Issue by thaoz** [drizopoulos/JMbayes#3]
I am using dplyr (tidyverse) for data manipulation which returns a dataset in "tibble" format. The `survfitJM()` gives me error when I tried to predict survival for a new "tibble" data set.  The problem can be solved by transforming the tibble data  back to data frame class with `as.data.frame()`, however, I though, given so many people working with dyplyr,  maybe there should be a warning in the JMbayes package for this case. 
Please see the code example below:
`# minimal example `
`pbc2$status2 <- as.numeric(pbc2$status != "alive")`
`pbc2.id$status2 <- as.numeric(pbc2.id$status != "alive")`

`# we fit the joint model using splines for the subject-specific `
`# longitudinal trajectories and a spline-approximated baseline`
`# risk function`
`lmeFit <- lme(log(serBilir) ~ ns(year, 2), data = pbc2,
              random = ~ ns(year, 2) | id)`
`survFit <- coxph(Surv(years, status2) ~ drug, data = pbc2.id, x = TRUE)`
`jointFit <- jointModelBayes(lmeFit, survFit, timeVar = "year")`
`ND <- pbc2[pbc2$id == 2, ] # the data of Subject 2`
`ND1 <- as.tibble(ND)`

`survfitJM(jointFit, newdata = ND) # work`
`survfitJM(jointFit, newdata = ND1) # error`

**Comment by drizopoulos** [comment]
Thanks for reporting this. I’m aware of the issue, but in the help file of survfitJM() it is stated that argument ‘newdata’ should be a data.frame not a tibble. But you’re right, I may consider adding a warning in the package.
