### ISSUE TITLE
output mvJointModelBayes

### ISSUE THREAD

**Issue by Giusi78** [drizopoulos/JMbayes#36]
Dear Prof. Rizopoulos,

I'm running the following analysis:

long_ktv<-mvglmer(list(KTV~TIME + (TIME|ID)), data=LONG_SCORE, families=list(gaussian)

cox_ktv<-coxph(Surv(DAYS_AT_RISK, DEATH) ~ COUNTRY + AGE + SEX +DIABETES + HEART_COMPOSITE +SMOKING_STATUS, data=SCORE, model=TRUE)

joint_ktv<-mvJointModelBayes(long_ktv, cox_ktv, timeVar="TIME")

I cannot find in the output (summary(joint_ktv)) the "Event process" session and the association parameter alpha (Assoct) as when I run the simple JointModelBayes function. Where can I get this useful information? 

Moreover if I try to calculate AUC or the ROC curve I get this error:

aucJM(joint_ktv, LONG_SCORE, Tstart = 2, Thoriz = 8, idVar = "ID")

error: Mat::elem(): index out of bounds
Error in log_post_RE_svft(b, Data = Data) : 
  Mat::elem(): index out of bounds

roc_ktv<-rocJM(joint_ktv, LONG_SCORE, Tstart=2, Dt=6, idVar = "ID")

error: Mat::elem(): index out of bounds
Error in log_post_RE_svft(b, Data = Data) : 
  Mat::elem(): index out of bounds

What is wrong?

Thank you for your help!

**Comment by drizopoulos** [comment]
Indeed, in `mvJointModelBayes()` the association parameter has the name of the longitudinal outcome with the default functional form being the current value, i.e., you should see in the output `KTV_value`.

With regard to the error in `aucJM()` check if there are events in this interval and or whether some longitudinal measurements were taken at exactly time 2 or 8. You could add or subtract to them a small quantity, e.g., `1e-06`.
