### ISSUE TITLE
Error in { :    task 1 failed - "Not compatible with requested type: [type=NULL; target=double]." Timing stopped at: 0.7 2.84 9.96

### ISSUE THREAD

**Issue by quzhouxiachuan** [drizopoulos/JMbayes#37]
I had this error when running 
multJMFit1 <- mvJointModelBayes(multMixedFit1, coxfit1, timeVar = "Time")

Error in { : 
  task 1 failed - "Not compatible with requested type: [type=NULL; target=double]."
Timing stopped at: 0.7 2.84 9.96

I also installed the github version of JMbayes. Any idea what is going on? 
Thanks, 
Yu

**Comment by drizopoulos** [comment]
Do you have a reproducible example?

**Comment by quzhouxiachuan** [comment]
I am not able to provide the data set unfortunately due to data privacy issue. However, when I am in debug mode, it shows that the elapsed_time function inside mvJointModelBayes() is where the problem is. Specifically, when running the line: 
`stopImplicitCluster()` inside the elapsed_time function
The error occurred. Not sure if this provides any clue?

Thanks, 
Yu

**Comment by quzhouxiachuan** [comment]
I think the step before stopImplicitCluster() which is runParallel is actually where the error came from.  
`runParallel(i, betas, b, sigmas, inv_D, inits,    Data, prs, scales, Cvs, con, typeSurvInf == "interval", multiState)` .

I noticed the $rows_wlongs in the Data parameter is all NULLs. Does this have things to do with the error message? This problem only happened after I updated the package to the github version. 

Thanks!

**Comment by quzhouxiachuan** [comment]
Also, not sure if this helps? I looked at the summary of the Data for runParallel command, and here is the results: 

Browse[2]> summary(Data)
                   Length Class  Mode     
y                      2  -none- list     
Xbetas                 2  -none- list     
X                      2  -none- list     
Z                      2  -none- list     
RE_inds                2  -none- list     
RE_inds2               2  -none- list     
idL                    2  -none- list     
idL2                   2  -none- list     
sigmas                 2  -none- list     
invD                   9  -none- numeric  
fams                   2  -none- character
links                  2  -none- character
Time                 186  -none- numeric  
event                186  -none- numeric  
idGK_fast            186  -none- numeric  
W1                  3162  -none- numeric  
W1s                47430  -none- numeric  
event_colSumsW1       17  -none- numeric  
W2                  1860  -none- numeric  
W2s                27900  -none- numeric  
event_colSumsW2       10  -none- numeric  
Wlong                372  -none- numeric  
Wlongs              5580  -none- numeric  
event_colSumsWlong     2  -none- numeric  
U                      2  -none- list     
Us                     2  -none- list     
col_inds               2  -none- list     
row_inds_U           186  -none- numeric  
row_inds_Us         2790  -none- numeric  
XXbetas                2  -none- list     
XXsbetas               2  -none- list     
XX                     2  -none- list     
XXs                    2  -none- list     
ZZ                     2  -none- list     
ZZs                    2  -none- list     
P                   2790  -none- numeric  
w                   2790  -none- numeric  
Pw                  2790  -none- numeric  
idT                    2  -none- list     
idTs                   2  -none- list     
outcome                2  -none- numeric  
indFixed               2  -none- list     
indRandom              2  -none- list     
trans_Funs             2  -none- character
nRisks                 1  -none- numeric  
kn_strat_last          1  -none- numeric  
kn_strat_first         1  -none- numeric  
idT_rsum             186  -none- numeric  
idT2                   2  -none- list     
idT2s                  2  -none- list     
rows_wlong         44386  -none- numeric  
rows_wlongs        44386  -none- list     
Levent1                0  -none- logical  
Levent01               0  -none- logical  
Levent2                0  -none- logical  
Levent3                0  -none- logical  
W1s_int                0  -none- logical  
W2s_int                0  -none- logical  
Wlongs_int             0  -none- logical  
Us_int                 1  -none- list     
XXsbetas_int           1  -none- list     
XXs_int                1  -none- list     
ZZs_int                1  -none- list     
P_int                  0  -none- numeric  
Pw_int                 0  -none- numeric

**Comment by drizopoulos** [comment]
Do you have a reproducible example?

**Comment by quzhouxiachuan** [comment]
Sorry for late reply. When I was preparing a simulation dataset for you, I found that applying as.numeric(ID_d) solved the problem. I think it might have things to do with the ID_d string being too long or the ID_d being factor variable. 
Thanks so much anyways!
