### ISSUE TITLE
How feasible to add  CompRisk option to 

### ISSUE THREAD

**Issue by swihart** [drizopoulos/JMbayes#39]
* Is it possible for a competing risks model using `JMbayes::mvJointModelBayes()`?  Similar to [Slide 165 of your presentation](http://www.drizopoulos.com/courses/EMC/ESP72.pdf).

  * If not, how feasible would it be for`JMbayes::mvJointModelBayes()` to acquire `CompRisk=TRUE` option for fitting competing risks like  `JM::jointModel()`?  I'm willing to try a PR if it is deemed feasible.  Any tips on where in the code to start?

Thanks, as always, for a great body of work and documentation.

**Comment by swihart** [comment]
This article seems to imply that no software as of June 2018 could do it:

["Competing risks [28, 29] and recurrent events [38] have been incorporated into joint modelling R packages already, but are limited to the case of a solitary longitudinal outcome. "](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6047371/#Sec14title)

**Comment by drizopoulos** [comment]
My PhD student Greg Papageorgiou has implemented a multi state models extension in JMbayes. This should also fit competing risks settings.

@Greg, could you provide an example.

**Comment by swihart** [comment]
I plan to add more to this, but for now I have equivalent CR and MS data prep/ Cox models.

````
library(JM)
library(JMbayes)
## slides: http://www.drizopoulos.com/courses/EMC/ESP72.pdf
## slide 163
pbc2.idCR <- crLong(pbc2.id, statusVar = "status",
                    censLevel = "alive", nameStrata = "CR")
pbc2.idCR[pbc2.idCR$id %in% c(1,2,5),
          c("id", "years", "status", "CR", "status2")]
## slide 164
coxFit.CR <- coxph(Surv(years, status2) ~ drug * strata(CR),
                   data = pbc2.idCR, x = TRUE)
coxFit.CR


## follow section 5 of 
## https://cran.r-project.org/web/packages/mstate/vignettes/Tutorial.pdf
pbc2.id[pbc2.id$id %in% c(1,2,5),
        c("id", "years", "status", "status2")]

library(mstate)
?trans.comprisk
tmat <- trans.comprisk(2, names = c("alive", "transplanted", "dead"))
tmat

pbc2.id$statTX <- as.numeric(pbc2.id$status=="transplanted")
pbc2.id$statDD <- as.numeric(pbc2.id$status=="dead")
?msprep
pbc2.idMS <- msprep(time =   c(NA, "years", "years"), 
                    status = c(NA, "statTX", "statDD"), 
                    data = pbc2.id, 
                    keep = "drug", 
                    trans = tmat)

pbc2.idMS[pbc2.idMS$id %in% c(1,2,5),
        c("id", "years", "status", "status2")]

coxFit.MS <- coxph(Surv(time, status) ~ drug * strata(trans),
                   data = pbc2.idMS, x = TRUE)
coxFit.MS
````

**Comment by swihart** [comment]
Notes as I try to debug:

Before Line 260 of `mvJointModelBayes`, `length(unique(dataL[[idVar]]))` is 312, `length(dataS[[idVar]])` is 0, and `idT` is not defined yet.

After the line 261 ` idT <- dataS[[idVar]] <- unique(dataL[[idVar]])`,  `length(unique(dataL[[idVar]]))` is 312, `length(dataS[[idVar]])` is 624, and `length(idT)` is 312.

**Comment by gpapageorgiou** [comment]
Dear @swihart, 

Below the code to reproduce the Competing Risks example of package **JM** using `JMbayes::mvJointModelBayes()`

`
library(JMbayes)
library(mstate)
library(splines)
library(survival)

# Prepare Dataset 
pbc2.id$death <- ifelse(pbc2.id$status %in% "dead", 1, 0)
pbc2.id$transplant <- ifelse(pbc2.id$status %in% "transplanted", 1, 0)

# Create transition matrix
tmat <- matrix(NA, 3, 3)
dimnames(tmat) <- list(from = c("alive", "transplanted", "dead"), 
                       to = c("alive", "transplanted", "dead"))
tmat[1, 2:3] <- 1:2

# Create Multi-state version of the dataset
covs <- c("drug", "sex")
pbc2.mstate <- msprep(time = c(NA, "years", "years"), 
                      status = c(NA, "transplant", "death"), 
                      data = pbc2.id, 
                      trans = tmat, 
                      keep = covs, 
                      id = "id")

# Expand covariates per transition
pbc2.mstate <- expand.covs(pbc2.mstate, covs, append = TRUE, longnames = FALSE)

# Fit Competing risks sub-model. Here, drug.1, drug.2, sex.1, sex.2 are the expanded covariates from the # previous step, with drug.1 for example representing the effect of drug for transition 1, drug.2 the effect # of drug for transition 2 etc.
coxCRfit <- coxph(Surv(Tstart, Tstop, status) ~ drug.1 + drug.2 + sex.1 + sex.2 + 
                        strata(trans) + cluster(id), 
                      data = pbc2.mstate, x = TRUE, model = TRUE)

# fit mixed-effects sub-model
mixfit <- mvglmer(list(log(serBilir) ~ drug * ns(year, 3) + (ns(year, 3) | id)), 
                  data = pbc2, 
                  families = list(gaussian))

# Specify interactions in order to allow different effect of the outcome for each risk
interacts <- list("log(serBilir)" = ~ strata(trans) - 1)

# fit multistate model
JMfit <- mvJointModelBayes(mixfit, coxCRfit, timeVar = "year",
                           Interactions = interacts, 
                           multiState = TRUE, 
                           data_MultiState = pbc2.mstate, 
                           idVar_MultiState = "id", 
                           control = list(equal.strata.knots = TRUE, 
                                          equal.strata.bound.knots = TRUE))

summary(JMfit)`

**Comment by swihart** [comment]
Thanks @gpapageorgiou and @drizopoulos !  I'm leaving an updated version of what I attempted above FWIW -- comments welcomed but not necessary, of course!  Thanks for your help and promptitude!

````
library(JM)
library(JMbayes)

##############################
## Do things the JM, CR way ##
## Limited to 1 longitudinal##
## process                  ##
##############################

## slides: http://www.drizopoulos.com/courses/EMC/ESP72.pdf
## slide 163
pbc2.idCR <- crLong(pbc2.id, statusVar = "status",
                    censLevel = "alive", nameStrata = "CR")
pbc2.idCR[pbc2.idCR$id %in% c(1,2,5),
          c("id", "years", "status", "CR", "status2")]
## slide 164
coxFit.CR <- coxph(Surv(years, status2) ~ drug * strata(CR),
                   data = pbc2.idCR, x = TRUE)
## equivalently:
pbc2.idCR$drug.1 <- (pbc2.idCR$drug=="D-penicil" & pbc2.idCR$CR=="transplanted")+0L
pbc2.idCR$drug.2 <- (pbc2.idCR$drug=="D-penicil" & pbc2.idCR$CR=="dead"        )+0L
coxFit.CR2<- coxph(Surv(years, status2) ~ drug.1 + drug.2 + strata(CR),
                   data = pbc2.idCR, x = TRUE)


## slide 164 & 165
lmeFit.CR <- lme(log(serBilir) ~ drug * year, data = pbc2,
                 random = ~ year | id)

jointFit.CR <- jointModel(lmeFit.CR, coxFit.CR, timeVar = "year",
                          method = "spline-PH-aGH", CompRisk = TRUE,
                          interFact = list(value = ~ CR, data = pbc2.idCR))

## same as jointFit.CR -- different parameterization (use coxFit.CR2 and change interFact).
jointFit.CR2<- jointModel(lmeFit.CR, coxFit.CR2, timeVar = "year",
                          method = "spline-PH-aGH", CompRisk = TRUE,
                          interFact = list(value = ~ strata(CR) - 1, data = pbc2.idCR))



###################################
## Do things the JMbayes, MS way ##
## Allows competing risks and >1 ##
## longitudinal process          ##
###################################
library(mstate)


## follow section 5 of
## https://cran.r-project.org/web/packages/mstate/vignettes/Tutorial.pdf
pbc2.id[pbc2.id$id %in% c(1,2,5),
        c("id", "years", "status", "status2")]


## prepare tmat
tmat <- trans.comprisk(2, names = c("alive", "transplanted", "dead"))
tmat
## use msprep()
pbc2.id$statTX <- as.numeric(pbc2.id$status=="transplanted")
pbc2.id$statDD <- as.numeric(pbc2.id$status=="dead")
?msprep
pbc2.idMS <- msprep(time =   c(NA, "years", "years"),
                    status = c(NA, "statTX", "statDD"),
                    data = pbc2.id,
                    keep = "drug",
                    trans = tmat)


## Crucial step!  I omitted this in my previous comment.
## Expand covariates per transition. See before/after expansion.
pbc2.idMS[pbc2.idMS$id %in% c(1,2,5),]
pbc2.idMS <- expand.covs(pbc2.idMS, "drug", append = TRUE, longnames = FALSE)
pbc2.idMS[pbc2.idMS$id %in% c(1,2,5),]


## explicitly put in the expanded covariates and add strata() and add cluster()
coxFit.MS <- coxph(Surv(Tstart, Tstop, status) ~ drug.1 + drug.2 + strata(trans) + cluster(id),
                   data = pbc2.idMS, model=TRUE, x=TRUE)

## reproduce jointFit.CR with mvglmer/mvJointModelBayes (?)
mvglmerFit.MS <- mvglmer(list(log(serBilir) ~ drug * year + (year|id)),
                         data = pbc2,
                         families=list(gaussian)
)


## Crucial step:
## Specify interactions in order to allow different effect of the outcome for each risk
interacts <- list("log(serBilir)" = ~ strata(trans) - 1)

jointFit.MS <-
  mvJointModelBayes(mvglmerFit.MS,
                    coxFit.MS,
                    timeVar="year",
                    Interactions=interacts,
                    multiState=TRUE,
                    data_MultiState=pbc2.idMS,
                    idVar_MultiState = "id",
                    control = list(equal.strata.knots=TRUE,
                                   equal.strata.bound.knots=TRUE)
  )



## similar:
summary(jointFit.CR2)
summary(jointFit.MS)


## similar:
coxFit.CR
coxFit.MS

## similar:
summary(lmeFit.CR)
summary(mvglmerFit.MS)

````

**Comment by harryparr** [comment]
Thanks for this tutorial @gpapageorgiou & @swihart. I was wondering if it was possible to perform dynamic predictions from a competing risk `mvJMbayes` object? I've attempted to do so with the following code:

```
ND <- pbc2[pbc2$id == 2, ] # the data of Subject 2
ND_merge <- merge(ND, coxCRfit$model, by.x = "id", by.y="(cluster)")
names(ND_merge)[names(ND_merge) == 'strata(trans)'] <- 'trans'
str(ND_merge)
'data.frame':	8 obs. of  26 variables:
 $ id                         : num  2 2 2 2 2 2 2 2
 $ years                      : num  14.2 14.2 14.2 14.2 14.2 ...
 $ status                     : Factor w/ 3 levels "alive","transplanted",..: 1 1 1 1 1 1 1 1
 $ drug                       : Factor w/ 2 levels "placebo","D-penicil": 2 2 2 2 2 2 2 2
 $ age                        : num  56.4 56.4 56.4 56.4 56.4 ...
 $ sex                        : Factor w/ 2 levels "male","female": 2 2 2 2 2 2 2 2
 $ year                       : num  0 0 4.9 4.9 7.89 ...
 $ ascites                    : Factor w/ 2 levels "No","Yes": 1 1 2 2 2 2 2 2
 $ hepatomegaly               : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2
 $ spiders                    : Factor w/ 2 levels "No","Yes": 2 2 2 2 2 2 2 2
 $ edema                      : Factor w/ 3 levels "No edema","edema no diuretics",..: 1 1 2 2 3 3 3 3
 $ serBilir                   : num  1.1 1.1 2.6 2.6 3.6 3.6 4.6 4.6
 $ serChol                    : int  302 302 230 230 244 244 237 237
 $ albumin                    : num  4.14 4.14 3.32 3.32 2.8 2.8 2.67 2.67
 $ alkaline                   : int  7395 7395 1110 1110 779 779 669 669
 $ SGOT                       : num  114 114 132 132 119 ...
 $ platelets                  : int  221 221 135 135 113 113 100 100
 $ prothrombin                : num  10.6 10.6 11.3 11.3 11.5 11.5 11.5 11.5
 $ histologic                 : int  3 3 3 3 3 3 3 3
 $ status2                    : num  0 0 0 0 0 0 0 0
 $ Surv(Tstart, Tstop, status): 'Surv' num [1:8, 1:3] (0,14.2+] (0,14.2+] (0,14.2+] (0,14.2+] ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : NULL
  .. ..$ : chr  "start" "stop" "status"
  ..- attr(*, "type")= chr "counting"
 $ drug.1                     : num  1 0 1 0 1 0 1 0
 $ drug.2                     : num  0 1 0 1 0 1 0 1
 $ sex.1                      : num  1 0 1 0 1 0 1 0
 $ sex.2                      : num  0 1 0 1 0 1 0 1
 $ trans                      : Factor w/ 2 levels "trans=1","trans=2": 1 2 1 2 1 2 1 2

survfitJM(CR_JMfit, ND_merge)
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels
```

The traceback shows below:
```
traceback()
8: stop("contrasts can be applied only to factors with 2 or more levels")
7: `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]])
6: model.matrix.default(term, data = newdata.GK.postRE.i)
5: model.matrix(term, data = newdata.GK.postRE.i)
4: FUN(X[[i]], ...)
3: lapply(TermsU, function(term) {
       model.matrix(term, data = newdata.GK.postRE.i)
   })
2: survfitJM.mvJMbayes(CR_JMFit, ND_merge)
1: survfitJM(CR_JMFit, ND_merge)
```
The error message is not too obvious to me and I don't see an apparent reason why it shouldn't work after combining the longitudinal and `msprep` data from the `cox$model` matrix. I don't see why the one-factor should be an issue when subsetting a singular patient. Any insight would be greatly appreciated. 

Harry

**Comment by gpapageorgiou** [comment]
@harryparr Thank you for your question.

Currently `survfitJM()` does not support `mvJMbayes` objects that were fitted using the argument `multistate = TRUE`. The actual error message is probably misleading in this case. Both the R and C++ parts of the source code would need to be adjusted for this to work. 

Best,
Greg
