### ISSUE TITLE
mvglmer and mvJointModelBayes coefficients are the same

### ISSUE THREAD

**Issue by lad1u13** [drizopoulos/JMbayes#40]
Hi there,

I apologise if this is due to my lack of understanding, but I noticed that the longitudinal coefficients from the mvglmer and mvJointModelBayes objects are exactly the same (betas, sigmas, and Ds). However, using the lme and jointModelBayes functions they differ (as I would expect).

Isn’t the idea behind the joint model that the survival information provides information for a better estimation of the random effects and the joint estimation leads to a reduction in bias in the beta coefficients? A reproducible example:

MixedModelFit1 <- mvglmer(list(log(serBilir) ~ year + (year | id)), data = pbc2,
                          families = list(gaussian))

pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
CoxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)

JMFit1 <- mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")
summary(JMFit1)

In this case the betas, sigmas and Ds are identical for MixedModelFit1 and JMFit1.

Many thanks,
Luke

**Comment by jpkrooney** [comment]
Hi,
I'm seeing the same thing as Luke. It would be good to know if this is by design or a bug, and if a bug are predictions also affected?
James

**Comment by drizopoulos** [comment]
mvJointModelBayes() implements a corrected two-stage approach, by first fitting the multivariate mixed model, then the survival sub-model updating also the random effects, and at the end use importance sampling weighting. For more info check here: http://www.drizopoulos.com/talk/ibc_2018/

The summary() method returns both the weighted and unweighted results. To get the weighted results use summary(..., weighted = TRUE)

**Comment by jpkrooney** [comment]
Ok thanks Dimitris I'll have a look there!
