### ISSUE TITLE
problem running function aucJM() in JMbayes package: Error in eigen

### ISSUE THREAD

**Issue by quzhouxiachuan** [drizopoulos/JMbayes#41]
I used aucJM() before and it was fine. However, when I included 4 longitudinal outcomes in the linear mixed model and used aucJM() to evaluate the joint model, it gives me the following error: 

aucJM(JMFit7, newdata=ND, Tstart=15, Thoriz = NULL, Dt = 10, idVar = 'ID_d') Error in eigen(Sigma, symmetric = TRUE) :    infinite or missing values in 'x'

I do not have missing data or infinite in the ND dataset. Any idea on what is going on here? Also, I have warning messages when fitting the mvJointModelBayes() function, I am not sure if this should be any concern. 

Thanks

**Comment by drizopoulos** [comment]
What is the output of traceback()?

**Comment by quzhouxiachuan** [comment]
Hi, 
Thanks for your quick reply! Here is the output from traceback: 
> traceback()
8: stop("infinite or missing values in 'x'")
7: eigen(Sigma, symmetric = TRUE)
6: (function (n, mu, Sigma, df) 
   {
       p <- length(mu)
       if (is.list(Sigma)) {
           ev <- Sigma$values
           evec <- Sigma$vectors
       }
       else {
           ed <- eigen(Sigma, symmetric = TRUE)
           ev <- ed$values
           evec <- ed$vectors
       }
       X <- drop(mu) + tcrossprod(evec * rep(sqrt(pmax(ev, 0)), 
           each = p), matrix(rnorm(n * p), n))/rep(sqrt(rchisq(n, 
           df)/df), each = p)
       if (n == 1L) 
           drop(X)
       else t.default(X)
   })(mu = dots[[1L]][[35L]], Sigma = dots[[2L]][[35L]], n = 100, 
       df = 4)
5: mapply(rmvt, mu = split(modes.b, row(modes.b)), Sigma = Vars.b, 
       MoreArgs = list(n = M, df = 4), SIMPLIFY = FALSE)
4: survfitJM.mvJMbayes(object, newdata = newdata2, idVar = idVar, 
       survTimes = Thoriz, M = M)
3: survfitJM(object, newdata = newdata2, idVar = idVar, survTimes = Thoriz, 
       M = M)
2: aucJM.mvJMbayes(JMFit7, newdata = NDD, Tstart = 15, Thoriz = NULL, 
       Dt = 10, idVar = "ID_d")
1: aucJM(JMFit7, newdata = NDD, Tstart = 15, Thoriz = NULL, Dt = 10, 
       idVar = "ID_d")
>

**Comment by drizopoulos** [comment]
The problems appears to be in the random effects covariance matrix. This could potentially suggest that you need to simplify your random effects structure.

**Comment by quzhouxiachuan** [comment]
Thanks! I will try to simplify it and see if the error gets solved. Right now, I only have a random slope: 
> #add more longitudinal outcomes 
> multMixedFit2 <- mvglmer(list(ln(TOTCHL) ~ Time + (Time | ID_d),
+                               ln(HDLCHL) ~ Time + (Time | ID_d),
+                               HXDIAB ~ Time + (Time | ID_d),
+                               SMOKER  ~ Time + (Time | ID_d) ), data = D, families = list(gaussian, gaussian,binomial, binomial))

**Comment by quzhouxiachuan** [comment]
Hi 
I changed the model to a simpler version:
 multMixedFit3 <- mvglmer(list(ln(TOTCHL) ~ Time + (Time | ID_d),
                              ln(HDLCHL) ~ Time + (Time | ID_d),
                              HXDIAB ~ Time + (1 | ID_d)
                             ), data = D, families = list(gaussian, gaussian,binomial))

However, same error still exists. Please let me know if there is a way around this. 
Thanks!

**Comment by quzhouxiachuan** [comment]
I also had this error when using aucJM(). I am not sure what is going on here. 


 aucJM(JMFit6, newdata=ND, Tstart=16, Thoriz = NULL, Dt = 10, idVar = 'ID_d')
Error in solve.default(opt$hessian) : 
  system is computationally singular: reciprocal condition number = 0

I am wondering if you have any thoughts on this? Any advice would be appreciated!

**Comment by drizopoulos** [comment]
This error originates in survfitJM() that is called from aucJM(). It 
indicates that for some subject the posterior of the random effects is 
not well specified.

Potential remedies could be to simplify the model and/or center 
predictors in the mixed model.



On 7/9/2019 6:12 AM, quzhouxiachuan wrote:
> I also had this error when using aucJM(). I am not sure what is going on 
> here.
> 
> aucJM(JMFit6, newdata=ND, Tstart=16, Thoriz = NULL, Dt = 10, idVar = 'ID_d')
> Error in solve.default(opt$hessian) :
> system is computationally singular: reciprocal condition number = 0
> 
> I am wondering if you have any thoughts on this? Any advice would be 
> appreciated!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2FJMbayes%2Fissues%2F41%3Femail_source%3Dnotifications%26email_token%3DADE7TT24PE42T5DKBHL6IRDP6QF35A5CNFSM4HMSJSVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZPAWFI%23issuecomment-509479701&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Ccd6397c1aefc42068e9608d70423b334%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C636982423679467067&sdata=j%2FpQefjUzRc%2F0U04a76fgtLZwAgzNnvgc5x%2FPRUITbo%3D&reserved=0>, 
> or mute the thread 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADE7TT57V6PYEYWLNAAWNITP6QF35ANCNFSM4HMSJSVA&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Ccd6397c1aefc42068e9608d70423b334%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C636982423679477059&sdata=TVqDRKHVZKD6TM6KxBki1DBH%2FH4ZdCNKZxdpkOk7f1U%3D&reserved=0>.
> 

-- 
Dimitris Rizopoulos
Professor of Biostatistics
Department of Biostatistics
Erasmus University Medical Center

Address: PO Box 2040, 3000 CA Rotterdam, the Netherlands
Tel: +31/(0)10/7043478
Fax: +31/(0)10/7043014
Web (personal): http://www.drizopoulos.com/
Web (work): http://www.erasmusmc.nl/biostatistiek/
Blog: http://iprogn.blogspot.nl/

**Comment by quzhouxiachuan** [comment]
Hi Thanks so much for the comments! Both my longitudinal variables are binary. I am afraid center predictors wouldn't work. The model works fine with continuous variables. 
I only have two longitudinal outcomes, so I wouldn't say the model is too complicated? See the code below: 
`
multMixedFit1 <- mvglmer(list(HXDIAB ~ Time + (Time | ID_d),
+                               SMOKER  ~ Time + (Time | ID_d) ), data = D, families = list(binomial, binomial))
JMFit1 <- mvJointModelBayes(multMixedFit1, coxfit1, timeVar = "Time")
`

**Comment by quzhouxiachuan** [comment]
actually, the error only occurs at some time points: 
<img width="718" alt="Screen Shot 2019-08-15 at 11 55 10 AM" src="https://user-images.githubusercontent.com/18423918/63107818-9f75d080-bf53-11e9-81de-c6e5e067a3c4.png">
