### ISSUE TITLE
Problem running JM: Error in optim

### ISSUE THREAD

**Issue by Yixin95** [drizopoulos/JMbayes#42]
The codes are very amazing and helpful.  But I meet some problem when fit a joint model. Any help will be appreciated. 
When I try to fit a joint model, it gives the following mistakes:
Error in optim(thetas, opt.survSplinePH, gr.survSplinePH, method = "BFGS",  : 
non-finite value supplied by optim

I do not have missing value. The linear mixed model and relative risk model run well, and all the results are significant.

I also try to use other methods,  such as "piecewise-PH-GH" and "weibull-PH-GH", but it still does not work.

I also try the commands that you give on your book (Page 68) , put  (iter.EM = 80, tol3 = 1e-09, numeriDeriv = "cd", eps.Hes = 1e-04)  these words at the end of my command, but it still gives the similar mistake. I do not know how to deal with this problem. 

Thank you for your time!

**Comment by drizopoulos** [comment]
This is for JM not JMbayes
