### ISSUE TITLE
rocJM - `Error in if (x$diffType == "absolute") { : argument is of length zero`

### ISSUE THREAD

**Issue by harryparr** [drizopoulos/JMbayes#45]
Dear Dimitris, 

I'm having some issues running and plotting the output of the _rocJM_ function on a _jointmodelBayes_ object, I get the above error message. 

All of the of the list objects in rocJM exist so it is running, I perform sapply(rocJM, summary) and find there are NAs in $qSN (1 NA) $qSP (1 NA) and $qOverall (2 NAs), but it is not obvious why they are present and where the error message comes from. The overall output from the rocJm is:

```
Areas under the time-dependent ROC curves

Estimation: Monte Carlo ( samples)
Error in if (x$diffType == "absolute") { : argument is of length zero
```

I've tried variations of Tstart and Dt and simulate arguments and ideally, I wish to have Tstart=8, and predict the next two years to Thoriz = 10. The traceback() function gives me a lot of output. 

Let me know if you require further info, thanks
Harry

**Comment by harryparr** [comment]
I forgot to add _aucJM, dynCJM_ and _prederrJM_ (and integrated prediction error, `interval=TRUE`) all work fine.

**Comment by mpirikL** [comment]
@harryparr Did you close this issue because you found a solution?

**Comment by harryparr** [comment]
Hi @mpirikL 
It appears to be working for me. 
What's your `sessionInfo` ? 
I think having only `JMbayes` package loaded and not with `JM` as well as having the most up-to-date version of JMbayes via Github `devtools::install_github("drizopoulos/JMbayes")` should help.

**Comment by mpirikL** [comment]
@harryparr, 
Thanks much for your suggestion. Not loading JM was the key. 
L.W.
