### ISSUE TITLE
rocJM issue: Error in (function (x, vec, rightmost.closed = FALSE, all.inside = FALSE, : 'vec' must be sorted non-decreasingly and not contain NAs

### ISSUE THREAD

**Issue by Jingyan-uth** [drizopoulos/JMbayes#48]
Hi there, I have an issue when running rocJM after I got results from mvJointModelBayes. 
When I fit rocJM, I kept having Error as:
"Error in (function (x, vec, rightmost.closed = FALSE, all.inside = FALSE,  : 'vec' must be sorted non-decreasingly and not contain NAs"

And the following is the traceback:
8.stop("'vec' must be sorted non-decreasingly and not contain NAs")
7.(function (x, vec, rightmost.closed = FALSE, all.inside = FALSE, left.open = FALSE) { if (!identical(FALSE, is.unsorted(vec))) ...
6.mapply(findInterval, Q_points, split(times, fids))
5.right_rows(newdata, newdata[[timeVar]], newdata[[idVar]], GK_points_postRE)
4.survfitJM.mvJMbayes(object, newdata = newdata2, idVar = idVar, survTimes = Thoriz, M = M)
3.survfitJM(object, newdata = newdata2, idVar = idVar, survTimes = Thoriz, M = M)
2.rocJM.mvJMbayes(JMFit, newdata = test, Tstart = 2, Dt = 4)
1.rocJM(JMFit, newdata = test, Tstart = 2, Dt = 4)

Could please help give some advise?

Best,
Grace

**Comment by drizopoulos** [comment]
Do you have ties in your event times (i.e., event times that are exactly equal)?

**Comment by yishigrace** [comment]
Yes, the event times have ties. I found that the newdata in rocJM() was not sorted by time. It works using sorted data. Thanks!

**Comment by yishigrace** [comment]
And Just curious, although mvglmer() allows missing observations in longitudinal biomarkers, does the function mvglmer() requires that multiple longitudinal biomarkers put in  have same number of subject response?

Best,
Grace

**Comment by Lisaleg** [comment]
Hi there, 

I had the same error message when fitting a JM model. I had a lot of ties in the event times. Does JM handle time events? 

Thanks for reading!
Best, 

Lisa

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
