### ISSUE TITLE
Multivariate Joint model posterior means 

### ISSUE THREAD

**Issue by Giusi78** [drizopoulos/JMbayes#51]
Dear Prof. Rizopoulos,

I have some issues with the "mvJointModelBayes" output.
I used data without any transformation so I think the posterior means should be exponentiated in order to get Hazard Ratios, is that correct? Neverthless, as you can see in the following extract, if I exponentiate the Albumin value I get a HR=0.82 which is huge in terms of clinical relevance! 

                                PostMean  StDev  StErr      2.5%     97.5% P
ALBUMIN_value      -0.2012 0.0110 0.0003   -0.2248   -0.2002 0

Is there something wrong in the interpretation of the output?

**Comment by drizopoulos** [comment]
Indeed by exponentiating the coefficients you get the hazard ratios.




On 12/12/2019 10:28 AM, Giusi78 wrote:
> Dear Prof. Rizopoulos,
> 
> I have some issues with the "mvJointModelBayes" output.
> I used data without any transformation so I think the posterior means 
> should be exponentiated in order to get Hazard Ratios, is that correct? 
> Neverthless, as you can see in the following extract, if I exponentiate 
> the Albumin value I get a HR=0.82 which is huge in terms of clinical 
> relevance!
> 
> |PostMean StDev StErr 2.5% 97.5% P |
> 
> ALBUMIN_value -0.2012 0.0110 0.0003 -0.2248 -0.2002 0
> 
> Is there something wrong in the interpretation of the output?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2FJMbayes%2Fissues%2F51%3Femail_source%3Dnotifications%26email_token%3DADE7TT7IAWSWGY6TX6XEW73QYH73RA5CNFSM4JZ3PBWKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H77YTJQ&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Cd861e70224a443e4040408d77ee5a3fb%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637117397075209250&sdata=atuGWY811m5VV%2FapAQveHJcWwt8V2XcCXHtT17%2B6vzQ%3D&reserved=0>, 
> or unsubscribe 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADE7TTYQCET7PDL2WLIWSZTQYH73RANCNFSM4JZ3PBWA&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7Cd861e70224a443e4040408d77ee5a3fb%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637117397075209250&sdata=KRdvUKi9VSt8%2FWCXdYoMEDrATnVv5FYcxvpxTOMgKw0%3D&reserved=0>.
> 

-- 
Dimitris Rizopoulos
Professor of Biostatistics
Department of Biostatistics
Erasmus University Medical Center

Address: PO Box 2040, 3000 CA Rotterdam, the Netherlands
Tel: +31/(0)10/7043478
Fax: +31/(0)10/7043014
Web (personal): http://www.drizopoulos.com/
Web (work): http://www.erasmusmc.nl/biostatistiek/
Blog: http://iprogn.blogspot.nl/
