### ISSUE TITLE
Question about the importance sampling weights in JMbayes

### ISSUE THREAD

**Issue by chzhang25** [drizopoulos/JMbayes#52]
Hi,

When I compared the results of JMbayes and JM on the pbc example, I found that the results of JMbayes without weight (summary(JMFit1)) were closer to that of JM. However, the results with weight (summary(JMFit1, TRUE)) had differences with that of JM. 
I dug deeper and noticed the weights were dominated by one MCMC sample. In the 1000 weight values, one has value 0.982, meaning the sum of other 999 weights is only 0.018. In this way, the MCMC iteration with the maximum weight dominated the weighted posterior mean, and made the effects of other MCMC iterations close to 0.
In my opinion, JM is the most accurate since it uses full likelihood. JMbayes with weight should outperform that without weight. However, the above outputs are not consistent with my expectation. Could you help explain why this happens? Any comments or suggestions are welcome. Thank you.

A reproducible example:
set.seed(123)
library(JM)
pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
lmeFit <- lme(log(serBilir) ~ year, random = ~ year | id, data = pbc2)
coxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, x = TRUE)
JMFit <- jointModel(lmeFit, coxFit, timeVar = "year", method = "spline-PH-aGH")
summary(JMFit)

library(JMbayes)
MixedModelFit1 <- mvglmer(list(log(serBilir) ~ year + (year | id)), data = pbc2,
                          families = list(gaussian))
CoxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)
JMFit1 <- mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")
summary(JMFit1)  ## similar to the results of JM
summary(JMFit1,TRUE)  ##  different with the results of JM
summary(JMFit1$weights) ## the maximum of weights is 0.98

**Comment by drizopoulos** [comment]
Try the newer JMbayes2: https://drizopoulos.github.io/JMbayes2/
