### ISSUE TITLE
Problem with survfitJM function

### ISSUE THREAD

**Issue by ngwali** [drizopoulos/JMbayes#54]
Hello Dimitry;

I have serious issues with computing the predicted survival curves using the survfitJM when I fitted the mvJointModelBayes.

The following problems were encountered:

>sprobs <- survfitJM(JMFit, newdata=ND, idVar = "auslongid")

Error in UseMethod("survfitJM") : 
  no applicable method for 'survfitJM' applied to an object of class "mvJMbayes"

NB: Both JM and JMbayes libraries were loaded.

I still could get the function to work.

I will be very happy if you could help.

Thank you.

**Comment by drizopoulos** [comment]
The problem is that you have both **JM** and **JMbayes** loaded - try again with only **JMbayes** loaded.

**Comment by JianGuoZhou3** [comment]
![image](https://user-images.githubusercontent.com/20199977/112137304-6510f280-8bd0-11eb-90a3-c48fd6423931.png)
Hi @drizopoulos I re-load JMbayes, however, still error.

**Comment by JianGuoZhou3** [comment]
![image](https://user-images.githubusercontent.com/20199977/112139119-ad311480-8bd2-11eb-9140-5f9625221d1e.png)
