### ISSUE TITLE
anova function, or extracting DICs, for mvJointModelBayes object? 

### ISSUE THREAD

**Issue by harryparr** [drizopoulos/JMbayes#55]
Dear Prof. Rizopoulos

I was wondering if it were possible to extract the df, LPML, DIC & pD from a mvJointModelBayes object at all?

 `anova(mvJMB_object)` does not appear to work and it doesn't look obvious how to extract them from `mvJMB_object$statistics$...` 

Is there a way of calculating the DICs or comparing mvJMB objects at all? Any help and guidance would be greatly appreciated. 

Many thanks,
Harry

**Comment by ngwali** [comment]
I have a similar issue too. I will be very happy to get an answer for this as well
