### ISSUE TITLE
Computing Conditional Survival probabilities

### ISSUE THREAD

**Issue by ngwali** [drizopoulos/JMbayes#57]
Hello Dimitry;

Before I ask this question, no other pull request have been made concerning this

My problem:

> sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid")
Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds

I tried this with log=FALSE
> sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid", M = 200L, scale = 1.6, log = FALSE)
Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds

Also tried this : with log=TRUE

> sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid", M = 200L, scale = 1.6, log = TRUE)
Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds

This worked for me with the for loop option. 

Please also advice how to compute DIC from mvJMbayes

Thank you

**Comment by drizopoulos** [comment]
It is difficult to see what is going wrong without a reproducible example.



On 3/6/2020 1:26 AM, Co-creatorofGenes wrote:
> Hello Dimitry;
> 
> Before I ask this question, no other pull request have been made 
> concerning this
> 
> My problem:
> 
>     sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid")
>     Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds
> 
> I tried this with log=FALSE
> 
>     sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid", M = 200L,
>     scale = 1.6, log = FALSE)
>     Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds
> 
> Also tried this : with log=TRUE
> 
>     sprobs <- survfitJM(JMFit.lin, ND, idVar = "auslongid", M = 200L,
>     scale = 1.6, log = TRUE)
>     Error in GK_points_CumHaz[[i]][j, ] : subscript out of bounds
> 
> Please Advice on this
> 
> Thank you
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2FJMbayes%2Fissues%2F57%3Femail_source%3Dnotifications%26email_token%3DADE7TT5X5WGHALGXWFAMDZLRGA7LTA5CNFSM4LCVXL62YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IS6NQHQ&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C5ab14e9de61c41ebeb7d08d7c165070c%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637190511958556476&sdata=XqReHJICr3Qnh5XfcSzR3TqdISagXNmtyGGw%2BYUmdjU%3D&reserved=0>, 
> or unsubscribe 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADE7TT24SWZFOZCFRWST6L3RGA7LTANCNFSM4LCVXL6Q&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C5ab14e9de61c41ebeb7d08d7c165070c%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637190511958566477&sdata=8Hy2wnmGMStnVcp420S31UzQ0GdhODDQdFG57Wpr4Nk%3D&reserved=0>.
> 

-- 
Dimitris Rizopoulos
Professor of Biostatistics
Department of Biostatistics
Erasmus University Medical Center

Address: PO Box 2040, 3000 CA Rotterdam, the Netherlands
Tel: +31/(0)10/7043478
Fax: +31/(0)10/7043014
Web (personal): http://www.drizopoulos.com/
Web (work): http://www.erasmusmc.nl/biostatistiek/
Blog: http://iprogn.blogspot.nl/

**Comment by ngwali** [comment]
Hello Dimitris;

Sorry, this problem has been resolved. I got those errors because I was using individuals in the longitudinal data (long) to compute baseline event-free probs in the "probs <- survfitJM(JMFit.lin, ND, idVar = "auslongid")". I should have used the "long.id" data rather. 

Also, the dynamics version works well when I used the "Long" data in a for loop.

Merci Beaucoup!

Please Note:

Though I was unable to resolve my problem with getting estimates for Treat0 and Treat1 variables. I really need to know how I could estimate both treatment effects without hierarchical centring. Because Hierarchical centring changes the interpretation of the estimates. (This according to Prof Emmanuel Lesaffre, my formal instructor at UHasselt)
