### ISSUE TITLE
DIC Question Not Answered

### ISSUE THREAD

**Issue by ngwali** [drizopoulos/JMbayes#59]
Hello Dimitris;

Hope this shouldn't be a burden on your part. But there was one question about the DIC for the Joint Model which you did not answer. I get DIC for the mixed effect submodel. But After combining the Mixed Effect with the survival submodels, how can we calculate the DIC of this Joint Model.

For my situation, I simply compare models based on AUC and PE. i.e to choose from Value, or Value + Slope, or Cumulative effect.

Sorry for the numerous questions sir. I am ok with the AUC and PE.  Though the Joint model DIC is better here for making informed decisions.

Thanks :)

**Comment by drizopoulos** [comment]
Yes, this calculation is not currently performed in **JMbayes** for `mvJointModelBayes()` models. It will be available in the new **JMbayes2** package.
