### ISSUE TITLE
compare cox regression performance with dynamic risk predictin

### ISSUE THREAD

**Issue by quzhouxiachuan** [drizopoulos/JMbayes#6]
Hi 

I am wondering if there is a function that I could compare the AUC for cox regression model to the AUC of dynamic risk prediction (mvJointModelBayes object)? For example, to compare the prediction accuracy of cox model and dynamic risk model of subjects surviving at T7 given they are alive at T3? 

I am aware that aucJM() can calculate the auc of dynamic risk object, is there a equivalent one for simple cox regression object?

**Comment by thaoz** [comment]
I have the same question for the equivalence function to calculate AIC in a simple Cox model.

**Comment by drizopoulos** [comment]
The aucJM() should also work for Cox models - there is a method for it, e.g., 

aucJM(cox_obj, newdata = <your_data>, Tstart = 3, Dt = 4, timeVar = <your_time_var>, 
respVar = <longitudinal_outcome>, evTimeVar = <event_Time_variable>)

**Comment by thaoz** [comment]
Thank you, it works. It gives similar results to those from timeROC in my data. The option for respVar does not seem to play any role here I guess.

**Comment by drizopoulos** [comment]
respVar is actually needed if you had used another functional form in your Cox model, e.g., slope or cumulative effect.

**Comment by quzhouxiachuan** [comment]
Does timeVar play any role here considering that the cox model only uses data at baseline and no longitudinal data is used?

**Comment by drizopoulos** [comment]
Yes, you need to define it.


Sent with my iPhone - apologies for typos

**Comment by studerus** [comment]
I also want to compare the predictive performance of a joint survival model with a model using only baseline data. However, it seems to me that a comparison with a Cox model would be unfair since the survival submodel of the joint model is not a Cox model, but a a relative risk model with penalized-spline-approximated baseline risk function. Is there a way to calculate the performance of this relative risk model using only baseline data?

**Comment by BenGoudsmit** [comment]
Dear, when using aucJM for a (time-dependent) Cox model:

> aucJM(tdcox, newdata, Tstart = 0.25, Dt = 0.25, timeVar = "years", respVar = "measurements", evTimeVar = "status")

I get the following error:

Error in `[.default`(SurvT, !duplicated(id), 1) : 
  (subscript) logical subscript too long
In addition: Warning messages:
1: In Surv(Tstart, Tstop, binstatus) :
  Stop time must be > start time, NA created
2: In Surv(Tstart, Tstop, binstatus) :
  Stop time must be > start time, NA created
