### ISSUE TITLE
multivariate joint model for longitudinal outcomes

### ISSUE THREAD

**Issue by thaoz** [drizopoulos/JMbayes#61]
Hi Prof Dimitris, 
It is not an issue but rather a question re to the result of the multivariate joint model for longitudinal outcomes obtaining from mvglmer() function. I am looking at the association of the evolution of the two outcomes overtime. Is it possible to derive that from the random effect matrix D in the output using the following formula: Cov(slope1, slope2)/sqrt(Cov(slope1, slope1)xCov(slope2, slope2). Do you know any other ways to look at the association of evolutions?
Thank you

**Comment by jianguozhouzunyimedicaluniversity** [comment]
Hi, did you get any feedback?
Best,

**Comment by drizopoulos** [comment]
Yes, this will be the correpation between the two slopes that you can indeed interpret as the association of the evolutions.
