### ISSUE TITLE
error while excute “ sprobs <- survfitJM(JMFit,ND,idVar = 'id') ”

### ISSUE THREAD

**Issue by wulingyu1028** [drizopoulos/JMbayes#63]
library('JMbayes')
pbc2<- JMbayes::pbc2
set.seed(12345)
MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year|id),
                              hepatomegaly ~ year * sex + (year|id)),
                         data = pbc2,
                         families = list(gaussian,binomial))
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")

CoxFit <- coxph(Surv(year,event)~drug+age,
                data = pbc2.id,model=TRUE)

JMFit <- mvJointModelBayes(MixedModelFit,CoxFit,timeVar='year')
# calculate predictions of the conditional survival probabilities for Patient 81
ND <- pbc2[pbc2$id==81,]

ND <- pbc2[pbc2$id==25,]
sprobs <- survfitJM(JMFit,ND,idVar = 'id')
# Error in GK_points_CumHaz[[i]][j, ] : 下标出界

**Comment by ngwali** [comment]
Please try using 

##  sprobs <- survfitJM(JMFit, ND[1,], idVar = 'id')

This should work
