### ISSUE TITLE
aucJM Function start producing weired Error messages

### ISSUE THREAD

**Issue by ngwali** [drizopoulos/JMbayes#64]
Hello Professor Dimitris;

A lot has happened over the past few days. I hope this message finds you well. There are many issues that have been reported concerning the JMbayes package on github, but you for some reason did not provide answers to them. Sometime one has to go via difference gymnastic to get via. However, if you could take the time to answer the following question, I will be very happy.

Assume I execute all my mvJMbayes joint models well without issues.
The isse comes with computation of auJM as follows:

#> RDF<-xLong[order(xLong$auslongid, xLong$years),]
#> RDF<-as.data.frame(RDF)
#> aucJM(JMFit1,        RDF, Tstart = 2.5,Thoriz = 5.5, idVar = "auslongid") 
Error in survfitJM.mvJMbayes(object, newdata = newdata2, idVar = idVar,  : 
  'newdata' must be a data.frame with more than one rows.

## Now Lets check your underlying code in generating this message:

#> if (!is.data.frame(RDF) || nrow(RDF) == 0)
#+     stop("'newdata' must be a data.frame with more than one rows.\n")
# >

Again Lets check 
#>!is.data.frame(RDF)
[1] FALSE

#> nrow(RDF)==0
[1] FALSE
#> 
So there is no problem whatsoever with my RDF data frame, since it is data frame and the number of rows is not equal to zero,
what then could be preventing me from computing the AUC?

**Comment by drizopoulos** [comment]
This error indicates that probably some subjects do not have any longitudinal measurements before the `Tstart` time.

**Comment by ngwali** [comment]
> This error indicates that probably some subjects do not have any longitudinal measurements before the `Tstart` time.

## Thank you Prof. That is TRUE. 

## Now: For those who have similar problems, please ensure that longitudinal measurements are available for subjects, and use a suitable Tstart and Tstop times. If not you will have thesame problem like me. 

Thank you sir.
