### ISSUE TITLE
problem in difference results with JM and JMbayes results

### ISSUE THREAD

**Issue by Samaneh-stat** [drizopoulos/JMbayes#65]
the significant difference between JM and JM bayes results. totally different value of the association parameter. Would you please kindly help me with that?

time varying linear covariates=fpgmmol
outcome=Diabetes
the results of JM is more convenient, however I should use JMbayes in this project.

lmeFit.slp1 <- lme(fpgmmol~time_y, random = ~ time_y | code, data = DM1, control = lmeControl(opt = 'optim'))
 coxFit.DM1 <- coxph(Surv(DMsurv_y2, Diabet123456) ~sex_0+age_0 ,data = DM2, x = TRUE,model=TRUE)
jointFit.DM1 <- jointModel(lmeFit.slp1, coxFit.DM1, timeVar = "time_y", method = "piecewise-PH-GH")
jointFit.DM2 <- jointModelBayes(lmeFit.slp1, coxFit.DM1, timeVar = "time_y", n.iter = 100)

JMbayes results:

Joint Model Summary:
Longitudinal Process: Linear mixed-effects model
Event Process: Relative risk model with penalized-spline-approximated
                baseline risk function
Parameterization: Time-dependent value

Variance Components:
             StdDev    Corr
(Intercept)  0.3881  (Intr)
time_y       1.6831 -0.2296
Residual     1.1200        

Coefficients:
Longitudinal Process
             Value Std.Err Std.Dev    2.5%  97.5%      P
(Intercept) 4.9884  0.0008  0.0082  4.9733 5.0086 <0.001
time_y      0.0325  0.0037  0.0291 -0.0162 0.0938   0.24

Event Process
            Value Std.Err  Std.Dev       2.5%      97.5%      P
sex_0    296.4636     NaN   0.0000   296.4636   296.4636 <0.001
age_0     18.5436     NaN   0.0000    18.5436    18.5436 <0.001
Assoct -1794.7439     NaN   0.0000 -1794.7439 -1794.7439 <0.001
tauBs   1808.5667 59.3673 593.6729  1041.1318  3166.0237     NA

MCMC summary:
iterations: 100
adapt: 3000 
-------------
Joint model code:

lmeFit.slp1 <- lme(fpgmmol~time_y, random = ~ time_y | code, data = DM1, control = lmeControl(opt = 'optim'))
 coxFit.DM1 <- coxph(Surv(DMsurv_y2, Diabet123456) ~sex_0+age_0 ,data = DM2, x = TRUE,model=TRUE)
jointFit.DM1 <- jointModel(lmeFit.slp1, coxFit.DM1, timeVar = "time_y", method = "piecewise-PH-GH")

Joint Model Summary:
Longitudinal Process: Linear mixed-effects model
Event Process: Relative risk model with piecewise-constant
                baseline risk function
Parameterization: Time-dependent

   log.Lik      AIC      BIC
 -15939.71 31911.42 32005.19

Variance Components:
             StdDev    Corr
(Intercept)  0.3909  (Intr)
time_y       0.0280  0.7129
Residual     0.4850        

Coefficients:
Longitudinal Process
             Value Std.Err  z-value p-value
(Intercept) 4.9775  0.0104 478.0305 <0.0001
time_y      0.0346  0.0010  34.5138 <0.0001

Event Process
             Value Std.Err  z-value p-value
sex_0       0.5192  0.0802   6.4707 <0.0001
age_0       0.0446  0.0033  13.3309 <0.0001
Assoct      2.0380  0.0726  28.0551 <0.0001
log(xi.1) -18.1700  0.5013 -36.2470        
log(xi.2) -16.7707  0.4913 -34.1330        
log(xi.3) -17.5461  0.5049 -34.7485        
log(xi.4) -17.7510  0.5858 -30.3047        
log(xi.5) -17.7983  0.6127 -29.0509        
log(xi.6) -17.9697  0.6526 -27.5338        
log(xi.7) -25.6966 28.3608  -0.9061        

Integration:
method: Gauss-Hermite
quadrature points: 9

Optimization:
Convergence: 0

**Comment by drizopoulos** [comment]
Could you try fitting with the adaptive Gaussian quadrature in JM, i.e., using method = “piecewise-PH-aGH”

Also, try mvJointModelBayes() in JMbayes, which is better.

Best,
Dimitris

**Comment by Samaneh-stat** [comment]
Thanks for your help. but with running "mvglmer" I get the following error, and even I could not solve it with set.seed.
> set.seed(123)
> MixedModelFit1 <- mvglmer(list(fpgmmol ~ time_y+ (time_y| code)), data = DM1,
+                           families = list(gaussian))
Warning message:
In gen.inits(inits, n.chains, seed, parallel) :
  The 'seed' argument will be deprecated in the next version. You can set it yourself with set.seed() instead.
> 
And

with using adaptive Gaussian quadrature in JM, i.e., using method = “piecewise-PH-aGH” I had the following message:

"infinite or missing values in Hessian at convergence"

please guide me on that.

Regards,
Samaneh

**Comment by drizopoulos** [comment]
The fact that the Hessian matrix is not positive definite perhaps indicates that the model is too complex for the data at hand. Try to simplify it.

**Comment by Samaneh-stat** [comment]
But its only a random intercept and slope without any adjustment. However we have 2500 participants with 6 measurements. That could be the reason for?

Could you please help me on mvglmer" I get the following error, and even I could not solve it with set.seed.

set.seed(123)
MixedModelFit1 <- mvglmer(list(fpgmmol ~ time_y+ (time_y| code)), data = DM1,

·                              families = list(gaussian))

·

  *

Warning message:
In gen.inits(inits, n.chains, seed, parallel) :
The 'seed' argument will be deprecated in the next version. You can set it yourself with set.seed() instead.

Regards,
Samaneh

**Comment by drizopoulos** [comment]
This is a warning message, not an error – you can ignore it.

**Comment by Samaneh-stat** [comment]
But not giving any results. Stop the analysis after warning and if require for summary gives me nothing.

**Comment by Samaneh-stat** [comment]
Error in using mvJointModelBayes

>  coxFit.DM1 <- coxph(Surv(DMsurv_y2, Diabet123456) ~sex_0+age_0 ,data = DM2, x = TRUE,model=TRUE)
> set.seed(123)
> MixedModelFit1 <- mvglmer(list(fpgmmol ~ time_y+ (time_y| code)), data = DM1,
+                           families = list(gaussian))

Warning message:
In gen.inits(inits, n.chains, seed, parallel) :
  The 'seed' argument will be deprecated in the next version. You can set it yourself with set.seed() instead.

> jointFit.DM3 <- mvJointModelBayes(lmeFit.slp1, coxFit.DM1, timeVar = "time_y")

Error in mvJointModelBayes(lmeFit.slp1, coxFit.DM1, timeVar = "time_y") : 
  object 'lmeFit.slp1' not found

> summary(jointFit.DM3 )

Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'object' in selecting a method for function 'summary': object 'jointFit.DM3' not found

**Comment by drizopoulos** [comment]
Does it work if you specify engine = STAN?

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by Samaneh-stat** [comment]
No its not work. Howerver, I could solve the JMbayes problem with specifying baseHaz = "regression-splines".
Many Thanks for your helps.

**Comment by drizopoulos** [comment]
Try the newer JMbayes2: https://drizopoulos.github.io/JMbayes2/
