### ISSUE TITLE
Feature request - beta regression as longitudinal subfamily

### ISSUE THREAD

**Issue by jpkrooney** [drizopoulos/JMbayes#66]
Hi,
I was wondering would it be possible to get beta regression added as a longitudinal sub-model family for dealing with longitudinal metrics that are proportions (for example oxygen saturation percentage). Some math background here: https://cran.r-project.org/web/packages/betareg/vignettes/betareg.pdf
I understand it might be a big ask, and so I understand if not possible!
Many thanks for a great package!

**Comment by drizopoulos** [comment]
That will be available in the JMbayes2 package.

**Comment by jpkrooney** [comment]
Wow fantastic - can't wait to try that out! Thanks again!
