### ISSUE TITLE
Error in solve.default(opt$hessian) 

### ISSUE THREAD

**Issue by Samaneh-stat** [drizopoulos/JMbayes#67]
Hello, 

I am running the following JM using JMbayes, but the following error is received :

> lmeFit.slp2 <- lme(fbs~ time_y2+sex_0+age_0+BMI_0+waist_0+sbp_0+hdl_0+tg_0+FHDM, random = ~time_y2| code, data = DM1, control = lmeControl(opt = 'optim'))
> coxFit.DM2 <- coxph(Surv(lastvisit, Diabet123456)~sex_0+age_0+BMI_0+waist_0+sbp_0+hdl_0+tg_0+FHDM ,data = DM2, x = TRUE,model=TRUE)
> jointFit.DM2 <- jointModelBayes(lmeFit.slp2, coxFit.DM2, timeVar = "time_y2", baseHaz = "regression-splines", verbose = FALSE,n.iter = 10)

Error in solve.default(opt$hessian) : 
  Lapack routine dgesv: system is exactly singular: U[5,5] = 0

could you please help me with that?

Regards,
Samaneh

**Comment by drizopoulos** [comment]
Could you try standardizing the covariates in the survival model
