### ISSUE TITLE
Error aucJM and prederrJM for time-dependent cox model

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JMbayes#68]
Dear prof Rizopoulos,

With the JMbayes package, I can calculate AUCs and prediction errors for my joint models.
Many thanks for your excellent work.
However, when doing the same for a simple time-dependent Cox model, I get an aucJM error, and NA's for prederrJM.
Due to my confidential data, I cannot provide a reprex.

Cox model:
tdcox <- coxph(Surv(Tstart, Tstop, binstatus) ~ score+ variable A+ variable B + variable C + variable D,
               data = trainingdata)

AUC:
> aucJM(tdcox, testdata, Tstart = 0.25, Dt = 0.25, timeVar = "years", respVar = "score", evTimeVar = "binstatus")

> Error in outer(fit$cumhaz, c(x2)) - fit$xbar : non-conformable arrays

Prediction errors:

>pred_err3mtest <- prederrJM(tdcox, testdata, Tstart = 0.25, Thoriz = 0.5, idVar = "id",timeVar = "years", respVar = "score", evTimeVar = "binstatus")
> pred_err3mtest[1]
> $prederr
> [1] NA

**Comment by drizopoulos** [comment]
Unfortunately, without a Reproducible example I cannot see what is going wrong.

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________

**Comment by BenGoudsmit** [comment]
In the JMbayes package, aucJM of TDC does (partly) work. 
Two questions:
- Why does the aucJM use less subjects for AUC calculation than the JM???
- Why is the performance of the JM lower?

> auc3m <- aucJM(JM,longtest,Tstart=0.25,Thoriz=0.50,idVar = "id")
> auc3m

	Time-dependent AUC for the Joint Model JM

Estimated AUC: 0.7737
At time: 0.5
Using information up to time: 0.25 (**4849** subjects still at risk)

> aucJM(tdcox, longtest, Tstart = 0.25, Dt = 0.25, timeVar = "years", respVar = "score", evTimeVar = "binstatus")

	Time-dependent AUC for the Cox Model tdcox

Estimated AUC: 0.9633
At time: 0.5
Using information up to time: 0.25 (**757** subjects still at risk)
