### ISSUE TITLE
Question on mvglmer()

### ISSUE THREAD

**Issue by mpirikL** [drizopoulos/JMbayes#69]
Good day,
I was wondering if you might help me understand some of the details of the relationship between the mvglmer() and mvJointModelBayes() functions. In particular, does the convergence details of the mvglmer() call matter? If the mvglmer() shows signs of not converging will that cause problems for the mvJointModelBayes()?

I seem to recall reading somewhere that in the univariate longitudinal response case, the joint model function, jointModelBayes() did not depend on the results of the longitudinal model, lme(). Have I misunderstood this? If not, is it the same for the multivariate longitudinal response case?

Thanks much for taking the time to answer my question.
L.W.

**Comment by drizopoulos** [comment]
In mvJointModelBayes() you would like to give a mvlgmer() model that converges nicely. If this model does not converge, then it indicates that it’s perhaps too complicated for the data at hand or that a scaling of the variables is required.

**Comment by mpirikL** [comment]
Thank you!
