### ISSUE TITLE
mvJointModelBayes

### ISSUE THREAD

**Issue by pczhang** [drizopoulos/JMbayes#7]
Hello,

I am trying out the example for mvJointModelBayes.

options(mc.cores = parallel::detectCores())
pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
MixedModelFit2 <- mvglmer(list(log(serBilir) ~ year + (year | id),
                                    spiders ~ year + (1 | id)), data = pbc2,
                               families = list(gaussian, binomial))
CoxFit2 <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)
JMFit2 <- mvJointModelBayes(MixedModelFit2, CoxFit2, timeVar = "year")

However, the program just hangs at mvJointModelBayes step. Nothing happen after that. "top" also shows no CPU usage. I am kind of confused, and not sure what I did wrong here.

Thanks,
Peng

**Comment by drizopoulos** [comment]
I cannot reproduce that - it works for me.

**Comment by pczhang** [comment]
I am having issues on both my laptop and desktop, though both have arch linux installed. In debug mode, the problem seems lie in doParallel.

in step mode, it stucks at
out1 <- foreach(i = block1, .packages = "JMbayes", .combine = c) %dopar% 
    {
        runParallel(i, betas, b, sigmas, inv_D, inits, Data, 
            prs, scales, Cvs, con, typeSurvInf == "interval")
    }

if I change %dopar% to %do%, it will run. It might be a problem of doParallel.

I will test it on another distribution when I get a chance.

**Comment by pczhang** [comment]
I tried on ubuntu on an aws ec2 instance. It is working. Still don't know why it is not on Arch linux. Do you have any suggestions? re-installing certain r packages? Or how to get debug info? Right now it just hangs on the above step with no cpu usage. thanks.

**Comment by pczhang** [comment]
simple example on doParallel does work.
such as
registerDoParallel(cores = 4)
x = foreach (i = 1:4) %dopar% i

I have also tried to replace doparallel with doMC. It doesn't work either for mvJointModelBayes.

**Comment by dwinsemius** [comment]
I'm having the same experience on an Ubuntu 18.04 installation of R 3.6.1 with recently installed JAGS and JMbayes (from CRAN). Monitoring processes with top shows that two cores are being used initially at 100% but then after a few minutes the %cpu time drops down to "caretaking" status of around 4% which is typical for just monitoring a console session. Further investigation showed that  behavior was triggered by the mvglmer call. When I separately ran the mvJointModelBayes call: top showed 8 cores opening briefly and then they shut down without apparently doing anything. And then the console showed no error or warning messages, but the process had evidently reached some sort of conclusion. 

(I'm not an experienced user of this package or even anything to do with JAGS. So if there's any sort of log to investigate I need a clue about where to look. I was just trying to answer a question on StackOverflow about an error using mvJointModelBayes.)

**Comment by drizopoulos** [comment]
I don't have Ubuntu and unfortunately it is difficult to see what is the 
source of this problem.



On 9/17/2019 7:47 PM, dwinsemius wrote:
> I'm having the same experience on an Ubuntu 18.04 installation of R 
> 3.6.1 with recently installed JAGS and JMbayes (from CRAN). Monitoring 
> processes with top shows that two cores are being used initially at 100% 
> but then after a few minutes the %cpu time drops down to "caretaking" 
> status of around 4% which is typical for just monitoring a console 
> session. Further investigation showed that behavior was triggered by the 
> mvglmer call. When I separately ran the mvJointModelBayes call: top 
> showed 8 cores opening briefly and then they shut down without 
> apparently doing anything. And then the console showed no error or 
> warning messages, but the process had evidently reached some sort of 
> conclusion.
> 
> (I'm not an experienced user of this package or even anything to do with 
> JAGS. So if there's any sort of log to investigate I need a clue about 
> where to look. I was just trying to answer a question on StackOverflow 
> about an error using mvJointModelBayes.)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdrizopoulos%2FJMbayes%2Fissues%2F7%3Femail_source%3Dnotifications%26email_token%3DADE7TTYW6JWLFBAIBNSX7TTQKEJ43A5CNFSM4EZUHLBKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD65K6RQ%23issuecomment-532328262&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C04481a8eeaea467ba36508d73b972de9%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637043392809641763&sdata=tiJyY%2FkIqU3nYgpDH%2BnGWk6GjqzrJUwiZY5Xm8DWzDg%3D&reserved=0>, 
> or mute the thread 
> <https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADE7TT7MCSZY5N3V2E2UUDTQKEJ43ANCNFSM4EZUHLBA&data=02%7C01%7Cd.rizopoulos%40erasmusmc.nl%7C04481a8eeaea467ba36508d73b972de9%7C526638ba6af34b0fa532a1a511f4ac80%7C0%7C0%7C637043392809651758&sdata=HrdDt3P8TVC%2BjMRwzkNq3cm5ImFD%2F0NslnAeQPEKblA%3D&reserved=0>.
> 

-- 
Dimitris Rizopoulos
Professor of Biostatistics
Department of Biostatistics
Erasmus University Medical Center

Address: PO Box 2040, 3000 CA Rotterdam, the Netherlands
Tel: +31/(0)10/7043478
Fax: +31/(0)10/7043014
Web (personal): http://www.drizopoulos.com/
Web (work): http://www.erasmusmc.nl/biostatistiek/
Blog: http://iprogn.blogspot.nl/

**Comment by AbubakerSuliman** [comment]
@dwinsemius and @pczhang the first two cores triggered by an internal call from `mvglmer` to `jagsUI::jags`'s :
From `?jagsUI::jags`
`n.cores If parallel=TRUE, specify the number of CPU cores used. Defaults to total available cores or the number of chains, whichever is smaller.`
The default for n.chains in `mvglmer` which is passed to `jags` is equal to 2. (see ?mvglmer, control section). Therefore we end up with parallel in only 2 cores. 

In Linux HPC node with 36 cores, I solve this issue using:
```
cl <- parallel::makeCluster(2, outfile="parallel.txt")
registerDoParallel(cl)
```

Instead of 

`registerDoParallel(cores=4)`

**Comment by kassayegetaneh** [comment]
Hello


I am trying out the example for mvJointModelBayes.

pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
MixedModelFit1<- mvglmer(list(log(serBilir) ~ year + (year | id),
data = pbc2,families = list(gaussian))

But unfortunately, i have got this:
Warning message:
In gen.inits(inits, n.chains, seed, parallel) :
  The 'seed' argument will be deprecated in the next version. You can set it yourself with set.seed() instead.

please help me  !!!!!

**Comment by kassayegetaneh** [comment]
Hello


I am trying out the example for mvJointModelBayes.

pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
MixedModelFit1<- mvglmer(list(log(serBilir) ~ year + (year | id),
data = pbc2,families = list(gaussian))

But unfortunately, i have got this:
Warning message:
In gen.inits(inits, n.chains, seed, parallel) :
  The 'seed' argument will be deprecated in the next version. You can set it yourself with set.seed() instead.

please help me  !!!!!

**Comment by drizopoulos** [comment]
You can ignore this warning message.

**Comment by kassayegetaneh** [comment]
OK!


Thanks !

**Comment by ctracz** [comment]
Instead of the warning mentioned above, I am getting this error: The seed argument is no longer supported, use set.seed() instead.
