### ISSUE TITLE
Can one use other another GLMM model object in mvjointmodelbayes()

### ISSUE THREAD

**Issue by mpirikL** [drizopoulos/JMbayes#72]
Is it possible to offer multivariate GLMMs fit by other algorithms, say rstanarm or brm, as input to mvJointModelBayes()? I ask because I am running into a consistent problem with mvglmer() that is not suffered by any of rstanarm or brm or rstan, when I code the model manually.

**Comment by drizopoulos** [comment]
Unfortunately, this is not possible.
