### ISSUE TITLE
Multivariate spline JM configuration

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JMbayes#73]
Dear prof. Rizopoulos,

I want to construct multivariate spline-based JMs in JMbayes, and also specify dForm so that both value and slope are used.
In your help file I only see examples of univariate spline-based mixed-effect models, e.g.:

linear mixed model with natural cubic splines for the time
effect
> lmeFit.pbc1 <- **lme(log(serBilir) ~ ns(year, 2), data = pbc2,
> random = ~ ns(year, 2) | id, method = "ML")**

With dForm for slope:

we include the time-dependent slopes term
> dForm <- list(fixed = ~ 0 + dns(year, 2), random = ~ 0 + dns(year, 2),
> indFixed = 2:3, indRandom = 2:3)

So far, I have constructed (working) mixed-effect models like this:

> mixedmodel_spline <- mvglmer(list(
>                                   log10A ~ ns(years, df=3) *(age + disease+ gender) + (years| id),
>                                   log10B ~ ns(years, df=3) *(age + disease + gender) + (years| id),
>                                   log10C ~ ns(years, df=3) *(age + disease+ gender) + (years| id),
>                                   log10D ~ ns(years, df=3) *(age + disease+ gender) + (years| id)),
>                              data = longtrain,
>                              families = list(gaussian, gaussian, gaussian, gaussian))

Is this correct?
Or should I add: random= list(id = pdDiag(form= ~ns(years, df=3)))?
And if so, what would the mvglmer formula be?

Lastly, what would the Forms argument look like for these 4 longitudinal measurements?
Something like this?

> Forms <- list(
>               "A" = "value",
>               "A" = list(fixed = ~ 0 + dns(years, df=3) + gender + disease+ age, random = ~ 0 + dns(years, df=3),
>                               indFixed = c(2:4,8:16), indRandom = c(2:4,8:16),name = "slope"), 
>               "B" = "value",
>               "B" = list(fixed = ~ 0 + dns(years, df=3) + gender + disease+ age, random = ~ 0 + dns(years, df=3),
>                               indFixed = c(2:4,8:16), indRandom = c(2:4,8:16),name = "slope"), 
>               "C" = "value",
>               "C" = list(fixed = ~ 0 + dns(years, df=3) + gender + disease+ age, random = ~ 0 + dns(years, df=3),
>                               indFixed = c(2:4,8:16), indRandom = c(2:4,8:16),name = "slope"), 
>               "D" = "value",
>               "D" = list(fixed = ~ 0 + dns(years, df=3) + gender + disease+ age, random = ~ 0 + dns(years, df=3),
>                               indFixed = c(2:4,8:16), indRandom = c(2:4,8:16),name = "slope") )

Many thanks for your efforts.

**Comment by drizopoulos** [comment]
The definition of dForm seems correct.

Regarding your multivariate mixed model, I cannot say if this “correct”; this depends on your data and the model you want to fit for each longitudinal outcome. But, in any case, this is a valid model.

**Comment by BenGoudsmit** [comment]
Dear,

Thanks for the reply.
After running for many hours, the specified mixed-effect model produces error: 

> Error in checkForRemoteErrors(val) : 
>   2 nodes produced errors; first error: Error in node (sqrt(tau1))
> Invalid parent values

I think this is JAGS related?

**Comment by BenGoudsmit** [comment]
What would a mvglmer specification look like for two linear (B and C) and one spline-modeled outcome (A) with  natural cubic splines for the time and also with flexible modelling of subject-specific longitudinal developments?
The code below does not work, what do I mis-specify?
Something like??:


> mixedmodel<- mvglmer(list(              
>   A~ ns(years, df=3) + gender + age + disease,
>  random= list(id = pdDiag(form= ~ns(years, df=3))),
>  B ~ years + age + gender + disease + (years | id),
>  C ~ years + age + gender + disease + (years | id)),
>                        data=longtrain,
>                        families=list(gaussian, gaussian, gaussian))

Of course, I would love to come to the EMC for a collaboration.

**Comment by drizopoulos** [comment]
You cannot fit a mixed model with a diagonal covariance matrix for the random effects in mvglmer() currently.

Best,
Dimitris
