### ISSUE TITLE
mvglmer() vs brm()

### ISSUE THREAD

**Issue by mpirikL** [drizopoulos/JMbayes#74]
Good day Dimitris,
I am having an issue with mvglmer fitting a particular longitudinal model. In the particular model (see codes below), the mvglmer() using Stan as the engine does a terrible job of sampling the posterior, when it does not crash R, whereas brms has no problem. I was hoping that you could help me understand what might be causing the drastic differences in these two algorithms. Also, maybe I can convince you to perhaps open up JMBayes so that it can accept longitudinal submodels from other packages; I'd be more than willing to help on this task. 

The particular call to mvglmer() is

`mvglmer_fit=mvglmer(formulas = list(scaled_log_AVAbyBSA~start_time+
                                       (start_time|id),
                                     scaled_log_AJV~start_time+
                                       (start_time|id),
                                     EF_cat~start_time+
                                       (start_time|id)),
                     data=results4,
                     engine = "STAN",
                     families = list(gaussian,gaussian,binomial),
                     control = list(n.chains=4,
                                    n.processors=4,
                                    n.iter=3000))`

The call to brms is:

`formula=mvbf(bf(scaled_log_AVAbyBSA ~ start_time + (start_time|p|id), family = gaussian()),
  bf(scaled_log_AJV ~ start_time + (start_time|p|id), family = gaussian()),
  bf(EF_cat ~ start_time + (start_time|p|id), family = bernoulli(link = "logit")))`

`brms_fit=brm(formula,
              data = results4,
              chains = 2,
              cores = 2,
              iter = 3000,
              control = list(adapt_delta = 0.9,
                             max_treedepth = 15))`

Thanks much for your help.
L.W.

**Comment by drizopoulos** [comment]
My team and I are currently working on a new implementation of JMbayes, i.e., JMbayes2, that will not rely on STAN or JAGS anymore. Given this development, we are now focusing more on this package than upgrading JMbayes. The first version is expected to be ready somewhere in October.
