### ISSUE TITLE
Different results with simple variables and mean-centralized variables

### ISSUE THREAD

**Issue by Samaneh-stat** [drizopoulos/JMbayes#77]
Hello  
we fit the joint model using splines for the subject-specific longitudinal trajectories and a regression-spline baseline hazard. 
the results are :+1: 
##############################################
Joint Model Summary:
Longitudinal Process: Linear mixed-effects model
Event Process: Relative risk model with spline-approximated 
                baseline risk function
Parameterization: shared random effects 

      LPML      DIC       pD
 -55454.69 111256.2 3785.229

Variance Components:
              StdDev
(Intercept) 5.833019
Residual    6.648113

Coefficients:
Longitudinal Process
              Value Std.Err Std.Dev    2.5%   97.5%      P
(Intercept) 88.9087  0.0282  0.1219 88.6773 89.0927 <0.001
time         0.2671  0.0079  0.0191  0.2296  0.3008 <0.001

Event Process
                     Value Std.Err Std.Dev    2.5%   97.5%      P
age3                0.0281  0.0034  0.0038  0.0236  0.0369 <0.001
waist3              0.0113  0.0005  0.0012  0.0096  0.0134 <0.001
height3            -0.0852  0.0005  0.0010 -0.0871 -0.0832 <0.001
tg3                -0.0012  0.0002  0.0003 -0.0018 -0.0009 <0.001
hdl3                0.0302  0.0022  0.0027  0.0263  0.0344 <0.001
sbp3                0.0271  0.0010  0.0015  0.0233  0.0288 <0.001
factor(FHDM3)1      0.2314  0.0374  0.0592  0.1310  0.3151 <0.001
Assoct:(Intercept)  0.7791  0.0021  0.0068  0.7689  0.7901 <0.001

        Dynamic Discrimination Index for the Joint Model jointFit.DM4

Estimated dynC: 0.915
In the time interval: [0, 12.4463]
Length of time interval: 12
######################

But the question is why with centralizing the variables the beta-coefficients as well as the DDI is changing. Normally i expected the same values for both. wold you please explain the problem?

### results with mean-centralizing

Joint Model Summary:
Longitudinal Process: Linear mixed-effects model
Event Process: Relative risk model with spline-approximated 
                baseline risk function
Parameterization: shared random effects 

      LPML      DIC       pD
 -55110.12 110523.9 3903.275

Variance Components:
              StdDev
(Intercept) 6.296184
Residual    6.218923

Coefficients:
Longitudinal Process
              Value Std.Err Std.Dev    2.5%   97.5%      P
(Intercept) 88.8751  0.0108  0.1076 88.6846 89.0763 <0.001
time         0.2774  0.0037  0.0157  0.2513  0.3091 <0.001

Event Process
                     Value Std.Err Std.Dev    2.5%  97.5%      P
age3_m              0.0160  0.0025  0.0052  0.0058 0.0270 <0.001
waist3_m            0.0292  0.0024  0.0055  0.0198 0.0402 <0.001
height3_m          -0.0039  0.0060  0.0092 -0.0200 0.0081   0.96
sbp3_m              0.0124  0.0011  0.0027  0.0086 0.0181 <0.001
tg3_m               0.0005  0.0001  0.0004 -0.0005 0.0013   0.20
hdl3_m              0.0286  0.0012  0.0032  0.0226 0.0339 <0.001
FHDM3_m             0.0461  0.0543  0.1200 -0.1427 0.2220   0.86
Assoct:(Intercept)  0.1397  0.0008  0.0060  0.1308 0.1523 <0.001

        Dynamic Discrimination Index for the Joint Model jointFit.DM12

Estimated dynC: 0.838
In the time interval: [0, 12.4463]
Length of time interval: 12

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
