### ISSUE TITLE
Error for myJointModelBayes

### ISSUE THREAD

**Issue by koji1225shasha** [drizopoulos/JMbayes#8]
I am having issues with myJointModelBayes, and am not sure how to resolve.

With the PBC data, I can run all the codes with the same results. When I try my own data, I receive an error message after running myJointModelBayes as below:
JMFit <- mvJointModelBayes(MixedModelFit, CoxFit, timeVar = "month")
Error in as.matrix(b[[ii]])[id[[ii]], indRandom[[i]], drop = FALSE] : 
  subscript out of bounds

When I have small sample size with only 10 samples, the code works. Any idea how to fix this. I appreciate your help, and wonderful contribution to the joint model.

**Comment by drizopoulos** [comment]
Thanks for reporting this! Could you send a reproducible example?

**Comment by quzhouxiachuan** [comment]
I have the same issue. The following code wil reproduce the error message: 

`pbc2.id$Time <- pbc2.id$years
pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
CoxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)
MixedModelFit1 <- mvglmer(list(log(serChol) ~ year + (year | id)), data = pbc2,
                          families = list(gaussian))
JM2= mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")`

Thanks!

**Comment by drizopoulos** [comment]
Try the newer JMbayes2: https://drizopoulos.github.io/JMbayes2/

**Comment by Zjj-nnnn** [comment]
> I have the same issue. The following code wil reproduce the error message:
> 
> `pbc2.id$Time <- pbc2.id$years` `pbc2.id$event <- as.numeric(pbc2.id$status != "alive")` `CoxFit <- coxph(Surv(Time, event) ~ drug + age, data = pbc2.id, model = TRUE)` `MixedModelFit1 <- mvglmer(list(log(serChol) ~ year + (year | id)), data = pbc2, families = list(gaussian))` `JM2= mvJointModelBayes(MixedModelFit1, CoxFit, timeVar = "year")`
> 
> Thanks!

Hello, I encountered the same problem when running the following code, which should be similar to your problem. Is there any solution?

>library("JMbayes")
>MixedModelFit <- mvglmer(list(prothrombin ~ year * sex + (year | id),
                              hepatomegaly ~ year * sex + (year | id)), data = pbc2,
                         families = list(gaussian, binomial))
>pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
>CoxFit <- coxph(Surv(years, event) ~ drug + age, data = pbc2.id, model = TRUE)
>JMFit <- mvJointModelBayes(MixedModelFit, CoxFit, timeVar = "year")

An error message is displayed:
Error in { : task 5 failed - "Cube::slice(): index out of bounds"
Timing stopped at: 0.35 0.22 301.7

**Comment by drizopoulos** [comment]
Try the newer package JMbayes2

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
