### ISSUE TITLE
Compare performance JM and Cox model

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JMbayes#80]
Dear prof. Rizopoulos,

Is there a way to compare a traditional cox.ph model (so not time-dependent) to aucJM and prederrJM performance at specific time points?
For example: compare e.g. 3-month prediction errors of a JM to a Cox model (for which the JM uses data up to 1 year).
For the JM this would be: prederrJM(JM, data, Tstart = 1, Thoriz = 1.25, idVar = "id") with t in years.

What is the best method to compute Cox prediction errors based on the population at t=1, for time t=1.25?

Thank you.

**Comment by drizopoulos** [comment]
See here: JMbayes:::prederrJM.coxph

**Comment by BenGoudsmit** [comment]
I fitted my traditional Cox model in the longitudinal data with the code below:
```
cox<- coxph(Surv(yrs,binstatus)~score, data=long)
coxpred_err3mtest <- prederrJM(cox, long, Tstart = 0.25, Thoriz = 0.5, idVar = "id",
                               respVar = "score", evTimeVar = "binstatus", timeVar = "yrs")
```
I get an error:
`Error in outer(fit$cumhaz, c(x2)) - fit$xbar : non-conformable arrays`

**Comment by drizopoulos** [comment]
You need a landmark dataset; see here for examples: https://github.com/drizopoulos/jm_and_lm/blob/master/case_study/AoValve_analysis.R

**Comment by BenGoudsmit** [comment]
I read through your code, I think I misunderstood the creation of the LM datafile.
```
# create LM data
    active_data <- AoValv[AoValv$EvTime > time & AoValv$time <= time, ]
```
Say I wanted to evaluate predictions at the abovementioned time t=1.25, would it then be?:
```
# create LM data
    active_data <- AoValv[AoValv$EvTime > 1 & AoValv$time <= 1.25, ]
```
