### ISSUE TITLE
In a JMBayes object, what is the relationship between the mcmc draws and the summary reports? 

### ISSUE THREAD

**Issue by mpirikL** [drizopoulos/JMbayes#81]
I have fit a JMBayes object with random intercept and time slope in the longitudinal submodel. Thus, the JMBayes object has mcmc draws for these random effects. For each individual in my observation set, it has 5000 (number of iterations) from the posterior distribution of these random effects. In the summary() report for the JMBayes objects, the random time slopes variance is reported as 2.2 or so. However, the variance of the posterior draws of all the time slope random effects is 0.75. There is not this kind of discrepancy with the intercept term, summary() report says the random intercept's variance is 0.49 and the variance of the mcmc draws from the random intercept's posterior is 0.48. Might you think of a reason for the giant discrepancy in the summary() reports variance and the mcmc draws variance in the random time slope? I thought maybe the posterior of the D matrix was being reported by the summary() function. But, the variance of the random time slopes according to the D matrix is 5.03 (mean value with standard deviation 0.2). The D matrix reports that the variance of the random intercepts is 0.014. 

I must be missing something. Intuitively, I would think that the mcmc draws from the posteriors of the random effects should match what is in the D matrix and both of these should match what is reported when I call summary(). Can someone help me understand what I am not understanding about these parts of the JMBayes object?

As a note, the mcmc draws for all the other parameters (betas, gammas, bs.gammas, sigma, alphas, Dalphas) all match what is reported by summary().

**Comment by drizopoulos** [comment]
check this: https://stats.stackexchange.com/questions/392283/interpreting-blups-or-varcorr-estimates-in-mixed-models/392307#392307
