### ISSUE TITLE
Extract JM estimated value and slope at time t

### ISSUE THREAD

**Issue by BenGoudsmit** [drizopoulos/JMbayes#83]
Dear prof,

What is the best way to assess the JM assumed value and slope of my longitudinal outcome at a certain time t?
E.g. patients are followed from day 0 to 50 and measured. I fit a JMbayes value and slope model.
How would I acquire the JM estimated value (predict()?) and slope at t=e.g. 25 or at time 125 (if there is a difference)?

Best,

Ben

**Comment by drizopoulos** [comment]
Dear Ben,

The standard version of joint models, but also of time-varying Cox models assumes that the association coefficient is the same for all time points. That is, the biomarker is time-varying, the coefficients for the biomarker not. There are version that relax this, i.e., to fit a model with a time-varying coefficient.

Best,
Dimitris
