### ISSUE TITLE
Error for jointModelBayes

### ISSUE THREAD

**Issue by JianGuoZhou3** [drizopoulos/JMbayes#84]
Hi @drizopoulos,
I got an error of jointModelBayes.

The code is 
![image](https://user-images.githubusercontent.com/20199977/113492501-06a11980-94d8-11eb-84a4-338f50e50fea.png)

![image](https://user-images.githubusercontent.com/20199977/113492463-cb064f80-94d7-11eb-8365-ddf6d30c863e.png)
But when  I translated time as time.year
````
CRP.ate$time.year<- CRP.ate$time/365
````
And retry it:
![image](https://user-images.githubusercontent.com/20199977/113492532-45cf6a80-94d8-11eb-82e9-dbb2ef8808fc.png)
However, there is another error.
![image](https://user-images.githubusercontent.com/20199977/113492542-57187700-94d8-11eb-8ec9-8896fdde8f94.png)
Could you please help me to check this?
Best,
JG

**Comment by JianGuoZhou3** [comment]
Other mvglmer related codes are worked.
![image](https://user-images.githubusercontent.com/20199977/113492572-9e9f0300-94d8-11eb-927b-4eee80348816.png)
![image](https://user-images.githubusercontent.com/20199977/113492598-caba8400-94d8-11eb-8f5b-6515c242259d.png)

**Comment by drizopoulos** [comment]
Better try JMbayes2
