### ISSUE TITLE
stan model does not contain samples 

### ISSUE THREAD

**Issue by yudeng2015** [drizopoulos/JMbayes#85]
Hi 
I am running mvglmer on my own dataset using the following code: 
`
 multMixedFit1 <- mvglmer(list(log(SBP) ~ Time  + (Time | ID_d),
                               log(TOTCHL) ~ Time  + (Time | ID_d),
                               SMOKER ~ Time + (Time | ID_d) ,
                               HXDIAB ~ Time + (Time | ID_d ),
                               log(HDLCHL) ~ Time + (Time|ID_d)), data = data.train ,
                          families = list(gaussian, gaussian, binomial, binomial ,gaussian), engine = 'STAN')
`

and it shows the following error message: 
`Stan model 'mv_glmer39325' does not contain samples.
Error in seq_len(d[2L]) : 
  argument must be coercible to non-negative integer
`
Also when I tried the default engine instead of stan, it showed the following error message: 
`Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: Error in node inv_D
Invalid parent values
`
Any idea what is going on here?

**Comment by drizopoulos** [comment]
Try JMbayes2

——
Dimitris Rizopoulos
Professor of Biostatistics
Erasmus University Medical Center
The Netherlands
________________________________
From: yudeng2015 ***@***.***>
Sent: Sunday, May 23, 2021 7:49:03 AM
To: drizopoulos/JMbayes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes] stan model does not contain samples (#85)


Hi
I am running mvglmer on my own dataset using the following code:
multMixedFit1 <- mvglmer(list(log(SBP) ~ Time + (Time | ID_d), log(TOTCHL) ~ Time + (Time | ID_d), SMOKER ~ Time + (Time | ID_d) , HXDIAB ~ Time + (Time | ID_d ), log(HDLCHL) ~ Time + (Time|ID_d)), data = data.train , families = list(gaussian, gaussian, binomial, binomial ,gaussian), engine = 'STAN')

and it shows the following error message:
Stan model 'mv_glmer39325' does not contain samples.
Error in seq_len(d[2L]) :
argument must be coercible to non-negative integer

Any idea what is going on here?
