### ISSUE TITLE
Bug in survfitJM results in error in aucJM

### ISSUE THREAD

**Issue by caterinagregorio** [drizopoulos/JMbayes#87]
In survfitJM:

lapply(last.time, function (t) survTimes[survTimes > t]) should be lapply(last.time, function (t) survTimes[survTimes >= t]).

This results in predictions not been made when the time of prediction is equal to the observed event time of the subject.
Moreover, this bug in survfitJM leads to an error in aucJM when the time horizon corresponds to some subject observed event time.

**Comment by drizopoulos** [comment]
Thanks for reporting. I'll have a look.

BTW, it would be better to use the newer JMbayes2 package.



From: Caterina Gregorio ***@***.***>
Sent: Wednesday, October 13, 2021 11:50 PM
To: drizopoulos/JMbayes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes] Bug in survfitJM results in error in aucJM (#87)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


In survfitJM:

lapply(last.time, function (t) survTimes[survTimes > t]) should be lapply(last.time, function (t) survTimes[survTimes >= t]).

This results in predictions not been made when the time of prediction is equal to the observed event time of the subject.
Moreover, this bug in survfitJM leads to an error in aucJM when the time horizon corresponds to some subject observed event time.

-

**Comment by caterinagregorio** [comment]
Thank you very much. The only reason  I am still using this package is that if I understood well the newer version does not allow to add a non-linear effect for the biomarker in the survival model yet.

Thank you again,
Best regards

**Comment by drizopoulos** [comment]
It is possible in the current GitHub version.

lmeFit <- lme(log(serBilir) ~ ns(year, 3, B = c(0, 14.5)) * sex, data = pbc2,
              random = ~ ns(year, 3, B = c(0, 14.5)) | id,
              control = lmeControl(opt = 'optim'))

pbc2.id$event <- as.numeric(pbc2.id$status != "alive")
CoxFit <- coxph(Surv(years, event) ~ drug + age, data = pbc2.id)

Forms <- ~ value(log(serBilir)) + poly2(value(log(serBilir))) +
        poly3(value(log(serBilir)))

jointFit <- jm(CoxFit, lmeFit, time_var = "year", functional_forms = Forms)
summary(jointFit)

**Comment by caterinagregorio** [comment]
That's really great! Thank you
