### ISSUE TITLE
Comparing two rocJM ROCs

### ISSUE THREAD

**Issue by alhbiostat** [drizopoulos/JMbayes#90]
Hi!

Is it possible to do a statistical comparison of two curves generated using rocJM, akin to the roc.test function from the package pROC?
I have two joint models, generated for the exact same individuals but using longitudinal measures for two different clinical variables, and want to test whether one measure is a stronger predictor of survival than the other (at a given point in time).

For example, a comparison of roc1 and roc2:
roc1 <- rocJM(jointFit.1 , newdata = var1 , Tstart = 14, Thoriz = 60, idVar = "ID")
roc2 <- rocJM(jointFit.2 , newdata = var2, Tstart = 14, Thoriz = 60, idVar = "ID")

Alternatively, is there a way to extract the patient event predictions so that the true and predicted status generated using the joint model can be used in pROC for this purpose.

Any help is much appreciated and thank you for a great tool!

**Comment by drizopoulos** [comment]
No, it is not possible to compare the ROCs like that. You could revert to JMbayes2 and compare the models instead using DIC and WAIC.

**Comment by alhbiostat** [comment]
Okay, thank you for the suggestion Dimitris.
