### ISSUE TITLE
Question about recurrent events model specificaition

### ISSUE THREAD

**Issue by jpkrooney** [drizopoulos/JMbayes#92]
Hi Dimitris,
Just looking through the vignette: https://drizopoulos.github.io/JMbayes2/articles/Recurring_Events.html

For the cox model specification:
`cox_fit <- coxph(Surv(tstart, tstop, status) ~ (group + age) : strata(strata),
                 data = cox_data)`

I notice the id argument is not specified here - is this not required for recurrent events model ?
Many thanks,
James

**Comment by drizopoulos** [comment]
Indeed, it is not required because it is recognized from the strata variable. That is, the first stratum corresponds to the recurrent events and the second stratum to a potential terminating event.

P.s., this question is for **JMbayes2** not **JMbayes**.
