### ISSUE TITLE
Adding covariates to both lme() and coxph()

### ISSUE THREAD

**Issue by axinaxia** [drizopoulos/JMbayes#93]
I am trying to understand if a covariate can influence both the longitudinal marker and survival outcome, should we add this covariate in both lme() and coxph() before running the joint model? Or is it enough just to add the covariate in one of them? Could you please give some advice? Thanks a lot!

**Comment by drizopoulos** [comment]
This will depend on your modeling aims. You may include the covariate in either or both submodels.
