### ISSUE TITLE
Time-dependent slope parameterization and  subjects with only one measurement

### ISSUE THREAD

**Issue by egenbrugge** [drizopoulos/JMbayes#94]
Dear Dimitris Rizopoulos,

I understood that mvglmer() needs at least one measurement per outcome and per subject and that it doesn't matter which measurement it is (i.e., at baseline or at a later time point).

I was wondering what happens if you instead of the current value you try to incorporate the slope of the longitudinal trajectory. Would you need at least two measurements per subject (and are those with only one measurement removed) or is the data handled differently by the package?

Many thanks in advance for your answer.

Kind regards

**Comment by drizopoulos** [comment]
You can still do the slope because it is the slope of the estimated longitudinal profile (that includes the fixed and random effects). You can estimate that even from subjects with one measurement.

**Comment by egenbrugge** [comment]
That makes sense. Thanks a lot for your quick response!
