### ISSUE TITLE
joint model for longitudinal and multi-state survival data can only handle non-missing data

### ISSUE THREAD

**Issue by egenbrugge** [drizopoulos/JMbayes#95]
Dear Dimitris Rizopoulos,

I have noticed that in general  mvJointModelBayes() can handle missing data quite well, both in the cox model and in the model for longitudinal data. However, if a joint model for longitudinal and multi-state survival data is fitted, then the mvJointModelBayes()  seems unable to handle missing data. The error message is like the following:

Error in `[[<-.data.frame`(`*tmp*`, state.id, value = c(1, 2, 1, 2, 1,  : 
  replacement has 904 rows, data has 880

After removing subjects with missing data this issue was resolved, but it took me a while to figure out what was going on. Maybe useful to have a more informative error message in the future?

Kind regards,

Els

**Comment by drizopoulos** [comment]
Try JMbayes2 instead.
