### ISSUE TITLE
Simple question related to interpretation of hazard ratio

### ISSUE THREAD

**Issue by smilesw** [drizopoulos/JMbayes#97]
Dear professor Rizopoulos 
I am using the JMbayes package to analyze longitudinal data.
Recently, I submitted to a journal and received the revision. 
The reviewer's question is how hazard ratio is interpreted (i.e. how high and low values influence the prediction). 
As for your tutorial article related to aortic root dimension, I understand that HR 1.14 for root dimension in JM1 means that an increase of 1mm in aortic root dimension would result in 1.14-fold increment in risk for aortic regurgitation.
Is this interpretation right? 
I want to hear confirmation from yours for the accurate publishment. 
Thanks in advance.

**Comment by drizopoulos** [comment]
Yes, this seems correct.
