### ISSUE TITLE
problem running fuction  mvJointModelBayes() in JMBayes package

### ISSUE THREAD

**Issue by amirabadiza921** [drizopoulos/JMbayes#98]
I had this error when running
model.cox<-coxph(Surv(surv_time,incidenceDM)~sex15_1+age+FHD+ waist+fbs+bs2HR+BMI,data=data.cox,x=T,model=TRUE)
summary(model.cox)
MixedModelFit2 <- mvglmer(list(logTSH ~ time + (time| id)), data = dataLong,
                          families = list(gaussian))
Forms <- list("logTSH" = "value","logTSH" = list(fixed = ~ 1, random = ~ 1,
   indFixed = 2, indRandom = 2, name = "slope"))

JMFit2 <- mvJointModelBayes(MixedModelFit2,model.cox, timeVar="time",Formulas = Forms)
summary(JMFit2)

Error in Zi*bi: non-conformable arrays
Thanks,

**Comment by drizopoulos** [comment]
Try [JMbayes2](https://drizopoulos.github.io/JMbayes2/).
