### ISSUE TITLE
problem running fuction mvJointModelBayes() in JMBayes package

### ISSUE THREAD

**Issue by amirabadiza921** [drizopoulos/JMbayes#99]
I had this error when running
model.cox<-coxph(Surv(time_event_1,incidenceCKD)~sex15_1+ageyr14+iffdm+ waist+fbs1+bs2hrs1+BMI,data=data.cox,x=T,model=TRUE)
summary(model.cox)
MixedModelFit2 <- mvglmer(list(logTSH ~ time + logAntiTpo+(time| code)), data = dataLong,
                          families = list(gaussian))
Forms <- list("logTSH" = "value",
              "logTSH" = list(fixed = ~ 1+logAntiTpo, random = ~ 1,
                                     indFixed = c(2,4), indRandom = 2, name = "slope"))
JMFit2 <- mvJointModelBayes(MixedModelFit2,model.cox, timeVar = "time",Formulas = Forms)
summary(JMFit2)

Error in marglogLik2(inits[c("Bs_gammas", "gammas", "alphas", "tau_Bs_gammas")],  : 
  failed to find initial values.

**Comment by drizopoulos** [comment]
Try the newer JMbayes2 package

From: amirabadiza921 ***@***.***>
Sent: Tuesday, May 9, 2023 11:56 AM
To: drizopoulos/JMbayes ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [drizopoulos/JMbayes] problem running fuction mvJointModelBayes() in JMBayes package (Issue #99)



Waarschuwing: Deze e-mail is afkomstig van buiten de organisatie. Klik niet op links en open geen bijlagen, tenzij u de afzender herkent en weet dat de inhoud veilig is.
Caution: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


I had this error when running
model.cox<-coxph(Surv(time_event_1,incidenceCKD)~sex15_1+ageyr14+iffdm+ waist+fbs1+bs2hrs1+BMI,data=data.cox,x=T,model=TRUE)
summary(model.cox)
MixedModelFit2 <- mvglmer(list(logTSH ~ time + logAntiTpo+(time| code)), data = dataLong,
families = list(gaussian))
Forms <- list("logTSH" = "value",
"logTSH" = list(fixed = ~ 1+logAntiTpo, random = ~ 1,
indFixed = c(2,4), indRandom = 2, name = "slope"))
JMFit2 <- mvJointModelBayes(MixedModelFit2,model.cox, timeVar = "time",Formulas = Forms)
summary(JMFit2)

Error in marglogLik2(inits[c("Bs_gammas", "gammas", "alphas", "tau_Bs_gammas")], :
failed to find initial values.

-
